#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Chenla Prolegomenon
#+STARTUP: showall
#+PROPERTY: filename 
#+INCLUDE: ./inc/head.org
#+HTML_HEAD: <link href="./css/index.css" rel="stylesheet" type="text/css" />
  :PROPERTIES:
  :Name: /home/deerpig/proj/deerpig/deerpig-install/index.org
  :Created: 2016-08-20T16:40@Wat Phnom (11.5733N17-104.925295W)
  :ID: 5995dc73-91da-4940-bae1-efb75ce040d4
  :URL:
  :END:
#+INCLUDE: ./inc/macros.org
#+INCLUDE: ./inc/links.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* About these pages

#+begin_quote
The Chenla Prolegomenon is a discursive narrative introduction to
Chenla's Big Picture.  It's expected that it will be broken into a
number of traditional books.
#+end_quote

* Recent Activity

Recent change activity on http://github.com/deerpig/deerpig-install

#+BEGIN_SRC sh :exports results :results silent
githubchart -u deerpig ./img/contrib.svg
#+END_SRC

#+RESULTS:

[[./img/contrib.svg]]

#+HTML: <div class="contrib-legend text-small text-muted" title="A summary of pull requests, issues opened, and commits to the default and gh-pages branches.">
#+HTML:  <span>Less</span>
#+HTML:   <ul class="legend">
#+HTML:     <li style="background-color: #eee"></li>
#+HTML:     <li style="background-color: #d6e685"></li>
#+HTML:     <li style="background-color: #8cc665"></li>
#+HTML:     <li style="background-color: #44a340"></li>
#+HTML:     <li style="background-color: #1e6823"></li>
#+HTML:   </ul>
#+HTML:  <span>More</span>
#+HTML: </div>

* Introduction

* Why?


** Against

The old argument that we as a civilization should concentrate on
spending resources to solve problems here on earth than to do things
like human exploration and colonization.

  - 
  - [[https://aeon.co/essays/is-a-mission-to-mars-morally-defensible-given-todays-real-needs][Is a mission to Mars morally defensible given today’s real needs?]] | Aeon Essays
  - [[https://qz.com/907211/should-we-live-on-mars-nasa-astronaut-ron-garan-believes-we-should-focus-on-fixing-problems-on-earth-instead-of-martian-colonization/][Should we live on Mars?]] | Quartz
  - [[http://www.foresight.org/nano/Mars.html][Space Development: The Case Against Mars]] | Eric Drexler
  - [[https://e4a-net.org/2017/01/24/why-were-not-going-to-mars-by-timothy-crownshaw/][Why we’re not going to Mars]] | Timothy Crownshaw – Economics for the Anthropocene

** For

#+begin_quote
  Look again at that dot. That's here. That's home. That's us. On
  it everyone you love, everyone you know, everyone you ever heard
  of, every human being who ever was, lived out their lives. The
  aggregate of our joy and suffering, thousands of confident
  religions, ideologies, and economic doctrines, every hunter and
  forager, every hero and coward, every creator and destroyer of
  civilization, every king and peasant, every young couple in love,
  every mother and father, hopeful child, inventor and explorer,
  every teacher of morals, every corrupt politician,
  every "superstar," every "supreme leader," every saint and sinner
  in the history of our species lived there--on a mote of dust
  suspended in a sunbeam.

  The Earth is a very small stage in a vast cosmic arena. Think of
  the rivers of blood spilled by all those generals and emperors so
  that, in glory and triumph, they could become the momentary
  masters of a fraction of a dot. Think of the endless cruelties
  visited by the inhabitants of one corner of this pixel on the
  scarcely distinguishable inhabitants of some other corner, how
  frequent their misunderstandings, how eager they are to kill one
  another, how fervent their hatreds.

  Our posturings, our imagined self-importance, the delusion that
  we have some privileged position in the Universe, are challenged
  by this point of pale light. Our planet is a lonely speck in the
  great enveloping cosmic dark. In our obscurity, in all this
  vastness, there is no hint that help will come from elsewhere to
  save us from ourselves.

  The Earth is the only world known so far to harbor life. There is
  nowhere else, at least in the near future, to which our species
  could migrate. Visit, yes. Settle, not yet. Like it or not, for
  the moment the Earth is where we make our stand.

  It has been said that astronomy is a humbling and
  character-building experience. There is perhaps no better
  demonstration of the folly of human conceits than this distant
  image of our tiny world. To me, it underscores our responsibility
  to deal more kindly with one another, and to preserve and cherish
  the pale blue dot, the only home we've ever known.

  -- Carl Sagan, Pale Blue Dot, 1994
#+end_quote


  - [[https://www.youtube.com/watch?v=ffUnNaQTfZE&t=1030][Supertasks]] | YouTube
  - [[https://www.youtube.com/watch?v=YH3c1QZzRK4][Wanderers]]  | YouTube
  - [[https://en.wikipedia.org/wiki/Pale_Blue_Dot][Pale Blue Dot]]  | Wikipedia
  - [[http://www.planetary.org/explore/space-topics/earth/pale-blue-dot.html][A Pale Blue Dot]] | The Planetary Society
  - [[https://www.youtube.com/watch?v=p86BPM1GV8M][Carl Sagan - Pale Blue Dot]] | YouTube
  - [[http://www.teslarati.com/yes-deserve-colonize-mars-keep-light-consciousness/][Yes, we deserve to colonize Mars and keep our “light of
    consciousness”]] | Teslarati

*** Carl Sagan Tribute Series

[[http://www.industrytap.com/wanderers-tormented-everlasting-itch-things-remote/24997][Wanderers Tormented with an Everlasting Itch for Things Remote]] | Industry Tap

- i [[https://www.youtube.com/watch?v=Qfm0GCvsIVA][  A Universe Not Made For Us]] | YouTube
- ii  [[https://www.youtube.com/watch?v=E6kStH-LXgI][Consider Again That Pale Blue Dot]] | YouTube
- iii [[https://www.youtube.com/watch?v=sKtHR1eUubI][Wanderers]] | YouTube




* Core Patterns

 - [[./prolog-cosmos.org][Cosmos]]
 - [[./prolog-process.org][Process]]
 - [[./prolog-holon.org][Holons]]
 - [[./prolog-identity.org][Identity]]
 - [[./prolog-pace.org][Pace Layers]]
 - [[./prolog-scope.org][Scope]]
 - [[./prolog-transactive.org][Transactive Nature]]

