#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Mind Introduction
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/mind-intro.org
  :Created: 2017-04-28T14:49@Prek Leap (11.642600N-104.919210W)
  :ID: 54b789ed-be8d-42f5-917f-266a986d7a31
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction



* Consciousness

Consciousness or the state of awareness of one self has more
baggage than [[https://en.wikipedia.org/wiki/Fahd_of_Saudi_Arabia][King Fahd]] on holiday.

Our conscious self-image is likely all there is to the soul.
And in many belief systems and cultures, our conscious
self-image is thought to be independent of the body and will
either transfer to another body after death or be
transported to another plane of existence where it will
continue on, as a incorporal spirit in place where we are
reunited with all of the other disembodied conscious
self-images.  Its such a bald-faced anthropomorphic concept
that it would be funny if it were not so nearly universally
believed in.  And the really bizzare thing is that many of
these belief systems claim that not only is the soul just
you without a mortal body, but that actions that you take on
earth determine if that eternity is spent in a bland boring
paradise or a twisted eternal punishment where mortal pain
is inflicted on an imortal non-corporal entity.  And this
lasts forever.

Why we find it so easy to believe in such preposterous
things is testimony to how weird and powerful conciousness
is.  We all know on at least an instinctive level that our
mind is not the same as our bodies -- that our thoughts do
not feel entirely tied to our senses and body.  It is not
obvious that our brains are constructing models of the world
that have reached a level of complexity that they are in
effect worlds in their own right.  The idea that our mind is
a ghost in the body's machine feels true.  That doesn't mean
that we are especially good at coming up with explanations
of what is happening, so we get the concept of souls -- and
if the soul is a ghost, there is no reason for the ghost to
not continue on without the body.  We /need/ such frameworks
to make sense of the world, to have a means of understanding
what we are, relative to each other and the world around us.

We just aren't very good at coming up with very imaginative
stories to explain it.

We project outselves into nature in the same way --
attributing human will and consciousness on natural forces
that are larger than we can control or understand.  We look
for meaning outside of ourselves and so project ourselves
into nature in the form of spirits, demons, ghosts, angels,
and gods.  And these become collective stories that become
cultural mythos that are the foundation for language and
social structures that go beyond hardwired instinctual group
bonding and behavior that predates even the limbic system.


* Experienced Reality as Illusion

Here we will explore how the brain constructs the illusion that we
percieve as reality.

#+begin_quote
In a nutshell, the brain builds models of the environment and the
body, which it uses to make hypotheses about the source of
sensations. The hypothesis that is deemed most likely becomes a
perception of external reality. Of course, the prediction could be
accurate or awry, and it is the brain’s job to correct for any errors
– after making a mistake it can modify its models to account better
for similar situations in the future.

But some models cannot be changed willy-nilly, for example, those of
our internal organs. Our body needs to remain in a narrow temperature
range around 37°C, so predictive processing achieves such control by
predicting that, say, the sensations on our skin should be in line
with normal body temperature. When the sensations deviate, the brain
doesn’t change its internal model, but rather forces us to move
towards warmth or cold, so that the predictions fall in line with the
required physiological state.

-- [[https://www.newscientist.com/article/2128725-a-guide-to-why-your-world-is-a-hallucination/][A guide to why your world is a hallucination]] | New Scientist
#+end_quote


The OpenMind project 


  - [[https://www.newscientist.com/article/2128725-a-guide-to-why-your-world-is-a-hallucination/][A guide to why your world is a hallucination]] | New Scientist


* Philosophy & Predictive Processing

  - [[http://predictive-mind.net/][Philosophy and Predictive Processing]] 

* Open Mind

  - [[http://open-mind.net/][OpenMind Project]]
