#   -*- mode: org; fill-column: 60 -*-

#+TITLE: The Great Plateau
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/prolog-great-plateau.org
:Created:   2017-09-20T19:43@Prek Leap (11.642600N-104.919210W)
:ID:        8118c15d-8977-4919-81dc-ec99879165a8
:VER:       559183480.839484216
:GEO:       48P-491193-1287029-15
:BXID:      proj:ROI4-2277
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

It's interesting that in all of the possible scenarios proposed to
answer Fermi's Paradox, the one that you hear little or nothnig about
is the idea that man doesn't destroy herself, but rather hits a
technological plateau where any future advances become so difficult
that they become a case of diminishing returns.

Man has hit many plateaus, some of which lasted milennia or at least
centuries.  In historical times these plateaus have often been called
dark ages, at least over the last two hundred years.  The average
person living in the middle of most of these dark ages wouldn't have
considered their time dark, just that not a lot changed.

The periods of plateau correspondended with no or low population
growth and though there were certainly no lack of wars, the wars just
sort of churned things rather than resulted in any great change.

The idea of a plateau runs counter to the whole modern notion of
progres.  A plateau is not a good thing.  It represents stagnation, of
staleness that if nothing else is just not very interesting.  Not a
lot of history emerges from dark ages because there wasn't a lot to
write about.  You had king following king following king, with the
wars that were fought between them, and that's about it.

But a plateau is not evil, it is neutral, neither progressing forward
or in decline.  For a species, a log sustained plateau is a the sign
of a highly successful species, who is well adapted to its ecological
niche and is not so specialized that it an ride out flucuations in the
the climate over long periods of time.

During plateaus, time is not thought of as linear but circular,
following the sun and the moon and the seasons.  What specific year it
was relative to centuries and milennia were not important.  Time was
relative to the solar cycles and to yourself and those around you in
your family, band or village.

But modern man wants none of that.
