#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Process
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/prolog-process.org
:Created:   2017-02-02T18:38@Prek Leap (11.642600N-104.919210W)
:ID:        fef5f13a-64d5-4c39-a800-7999196c68ff
:VER:       551830771.379088677
:GEO:       48P-491193-1287029-15
:BXID:      proj:LCA3-7365
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

 - APL & Nature of Order
 - Agile & Scrum
 - Process Philosophy
 - Recognitions
 - Emacs


* @jaan Notes

I touched on this today in chenla/docs/methodoligies file --
Agile/Scrum was inspired by APL & A Timeless Way of Building -- but
it's only based on the development process; not on the whole reason
for the process, which was to create buildings andf cities that have
QWAN.

I saw a comment on Reddit that said that Emacs had it, because it has
been around so long and developed iteratively to improve it -- not
just cosmetically but deep in its bones -- emacs is constantly
reinventing itself, while adhering to its core principles and all the
while shamelessly copying good ideas from everwhere, like English and
Cantonese.

Processes have centers as beautiful as any Rose window in a catherdral
and I think that Alexander would agree that at its best -- the process
that creates generative structures must be beautiful as well.

    generative processes -- a process that leads to stronger
reinforcing patterns -- which is the real definition of anything
that is antifragile.

It's easier to see centers in the physical world because you see a
snapshot -- the state of a process at a given moment -- bit I think
tha tthe physical state is an illusion -- and that the quality without
a name cannot be name because everything is in the process of becoming
something else. -- that beauty is the quality of processes which are
becoming stronger -- the opposite of this is decay -- entropy

The process of iterative development in Agile & Scrum is based on the
sludgey process Alexander has developed because we have forgotten how
to dance the process of creating life -- we need something far more
fundemental than Agile to build things that are beautiful because we
build things that are a natural expression of becoming --
unfolding... which largely boils down to /caring/ - at every level and
detail to do things right.

The Gaddis quote from the Recognitions -- of stone carvers spending
countless hours carving the backs of the heads of gargoyles that will
be in the roof details so high up that they will never be seen --
because /God/ sees.  /That/ is  what has been lost -- caring deeply as
if the very fabric of the universe hung on each descion you make in
the process because it does...

Stewart Brand got the idea of buildings as processes right in /How
Buildings Learn/  -- Alexander, as an architect, no so much.  To hom
when his part was done, so was the building, when in fact it was only
the beginning...

Agile doesn't address software as a process -- we still think of
software like the modern concept of a building -- after its built
there is just maintanence.  But maintenance is actually development
without the care.

Emacs is beautiful because it is never finished & people  care about
it.

Hiro's Sushi is all about process and deeply caring.  His achievement
is not just quality & beauty -- but consistency and reproducibility
and sustainibility.

Olson got this as well -- he said it as intellectual intensity and
deeply caring about whatever passed scrutiny of those bushy brows.
He got process -- Whithead -- and that all history was simultaneous --
as did Pound before him.

Perhaps it's Caxton who did us the great disservice of taming
Malory's magnificent rambling Arthurian Tale into a codex with a
beginning that led to a middle that led to an end.

Caxton, along with Ford's assembly line -- all tells us there is an
end to things -- that can be used up and discarded and become waste as
if they had found numbers that could not add another one to -- that
2+1 is impossible and that two must be discarded and tossed onto the
rubbish heap with all the other twos and then start out with a fresh
two....

* Recognitions Quotes

:NOTE: I think we will need the Piccaso Quote -- that you
can only see something seven times in a lifetime....

#+begin_quote
“That romantic disease, originality, all around we see originality of
incompetent idiots, they could draw nothing, paint nothing, just so
the mess they make is original... Even two hundred years ago who
wanted to be original, to be original was to admit that you could not
do a thing the right way, so you could only do it your own way. When
you paint you do not try to be original, only you think about your
work, how to make it better, so you copy masters, only masters, for
with each copy of a copy the form degenerates... you do not invent
shapes, you know them, /auswendig wissen Sie/, by heart...”
#+end_quote

#+begin_quote
It’s a question of... it’s being surrounded by people who don’t
have any sense of... no sense that what they’re doing means
anything. Don’t you understand that? That there’s any sense of
necessity about their work, that it has to be done, that it’s
theirs. And if they feel that way how can they see anything necessary
in anyone else’s? And it... every work of art is a work of perfect
necessity. 
#+end_quote

#+begin_quote
That’s what it... has to be, that’s all. And if everyone else’s
life, everyone else’s work around you can be interchanged and nobody
can stop and say, This is mine, this is what I must do, this is my
work... then how can they see it in mine, this sense of
inevitableness, that this is the way it must be. In the middle of all
this how can I feel that... damn it, when you paint you don’t just
paint, you don’t just put lines down where you want to, you have to
know, you have to know that every line you put down couldn’t go any
other place, couldn’t be any different... But in the midst of all
this... rootlessness, how can you... damn it, do you talk to
people? Do you listen to them?
#+end_quote


#+begin_quote
Do you think I do these the way all other forging has been done?
Pulling the fragments of ten paintings together and making one, or
taking a... a Dürer and reversing the composition so that the man
looks to the right instead of left, putting a beard on him from
another portrait, and a hat, a different hat from another, so that
they look at it and recognize Dürer there? No, it’s... the
recognitions go much deeper, much further back, and I... this
. . . the X-ray tests, and ultra-violet and infra-red, the experts
with their photomicrography and... macrophotography, do you think
that’s all there is to it? Some of them aren’t fools, they don’t just
look for a hat or a beard, or a style they can recognize, they look
with memories that... go beyond themselves, that go back to... where
mine goes.
#+end_quote

#+begin_quote
And... any knock at the door may be the gold inspectors, come to
see if I’m using bad materials down there, I... I’m a master
painter in the Guild, in Flanders, do you see? And if they come in and
find that I’m not using the... gold, they destroy the bad materials
I’m using and fine me, and I... they demand that... and this
exquisite color of ultramarine, Venice ultramarine I have to take to
them for approval, and the red pigment, this brick-red Flanders
pigment... because I’ve taken the Guild oath, not for the critics,
the experts, the... you, you have no more to do with me than if you
are my descendants, nothing to do with me, and you... the Guild
oath, to use pure materials, to work in the sight of God...
#+end_quote

#+begin_quote
This... these... the art historians and the critics talking
about every object and... everything having its own form and
density and... its own character in Flemish paintings, but is that
all there is to it? Do you know why everything does? Because they
found God everywhere. There was nothing God did not watch over,
nothing, and so this... and so in the painting every detail
reflects... God’s concern with the most insignificant objects in
life, with everything, because God did not relax for an instant then,
and neither could the painter then. Do you get the perspective in
this? he demanded, thrusting the rumpled reproduction before
them. — There isn’t any. There isn’t any single perspective, like the
camera eye, the one we all look through now and call it realism, there
... I take five or six or ten... the Flemish painter took twenty
perspectives if he wished, and even in a small painting you can’t
include it all in your single vision, your one miserable pair of eyes,
like you can a photograph, like you can painting when it... when it
degenerates, and becomes conscious of being looked at.
#+end_quote

#+begin_quote
Like everything today is conscious of being looked at, looked at by
something else but not by God, and that’s the only way anything can
have its own form and its own character, and... and shape and
smell, being looked at by God.
#+end_quote

#+begin_quote
How could Bach have accomplished all that he did? and Palestrina? the
Gabrielis? and what of the organ concerti of Corelli? Those were the
men whose work he admired beyond all else in this life, for they had
touched the origins of design with recognition. And how? with music
written for the Church. Not written with obsessions of copyright
foremost; not written to be played by men in worn dinner jackets, sung
by girls in sequins, involved in wage disputes and radio rights,
recording rights, union rights; not written to be issued through a
skull-sized plastic box plugged into the wall as background for
seductions and the funnypapers, for arguments over automobiles,
personalities, shirt sizes, cocktails, the flub-a-dub of a lonely girl
washing her girdle; not written to be punctuated by recommendations
for headache remedies, stomach appeasers, detergents, hair oil... /O
God! dove sei Fenestrula?/
#+end_quote
