#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Minimum & Maximum Viability
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-viability.org
  :Created: 2017-04-16T19:21@Prek Leap (11.642600N-104.919210W)
  :ID: 44a4538c-72b0-4ff3-a919-c75c1e67f08b
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Once we have accepted the wisdom of the LOCKSS model and that this
provides Mankind with it's best chance of maximizing it's long term
survival and sustained level of properity we face the rather daunting
task of determining what is the minimum size in terms of population,
technology, tools and skills required that constitute a sustainable
technological civilization.  That would give us a baseline for how
many instances of civilization that we can theoretically maintain
any given population.

As anyone who is familiar with maintaining computer backups, it is not
as simple a creating a bunch of copies.  There are many different
statistical models that can be used to determine how many copies can
be maintained in such a way that X number of copies can be destroyed
and still reconstitute anything that has been lost.  This means that
we don't have to use the same brute force duplication that DNA
employess to achieve the same results.  But before we can get into any
of that we need to determine a number of minimal viability parameters
that taken together constitute a sustainable civilization.

In one respect, this could be the single most important reason to go
to Mars other than Mars as a backup of Earth.  It may be impossible to
know for certain what real minimum viability is unless we can build
and demonstrate it in the real world, or at least on another, real
world like Mars.

Civilization is such a large, dynamic, complex system that it is like
the weather, the number of variables and interactions is beyond
meaningful prediction beyond very short term, and crude projects that
even then are not always accurate.

* Carrying Capacity 

  - [[https://en.wikipedia.org/wiki/Carrying_capacity][Carrying capacity]] | Wikipedia

A more common term for the maximum viability of an ecosystem is of
course its /carrying capacity/.

This is certainly not limited to humans -- when locust swarm they
quickly exhaust the carrying capacity of a region which results in a
collapse and die-off of the population.

Human civilization is an almost cyclical progression of successful
populations exceeding the carrying capacity of their ecosystems, at
which time there is collapse and a die-off.

The carrying capacity is not a hard number, it depends on a number of
different parameters that can be leveraged to increase or decrease
that capacity.  
