#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Information
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/prolog-information.org
:Created:   2017-08-12T18:07@Prek Leap (11.642600N-104.919210W)
:ID:        c0877bba-84d4-4638-9689-087d4fa7b8ba
:VER:       555808101.654176304
:GEO:       48P-491193-1287029-15
:BXID:      proj:LJV2-8836
:Class:     primer
:Type:      work
:Status:    stub
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction


#+begin_quote
There’s only meaning where there’s prior agreement about our
symbols. And all communication is like this, from waves sent over
electrical wires, to the letters agreed upon to symbolize words, to
the words agreed upon to symbolize things.

 -- [[http://nautil.us/issue/51/limits/how-information-got-re_invented][How Claude Shannon Rebooted Information]] | Nautilus
     [[bib:soni:2017mind][A Mind at Play]] |  Jimmy Soni & Rob Goodman (2017)
#+end_quote

#+begin_quote
The real measure of information is not in the symbols we send— it’s in
the symbols we could have sent, but did not. To send a message is to
make a selection from a pool of possible symbols, and “at each
selection there are eliminated all of the other symbols which might
have been chosen.” To choose is to kill off alternatives. Symbols from
large vocabularies bear more information than symbols from small
ones. Information measures freedom of choice.

 -- [[http://nautil.us/issue/51/limits/how-information-got-re_invented][How Claude Shannon Rebooted Information]] | Nautilus
    [[bib:soni:2017mind][A Mind at Play]] | Jimmy Soni & Rob Goodman (2017)
#+end_quote


#+begin_quote
  - The information source produces a message.  The transmitter encodes
  - the message into a form capable of being sent as a signal.  The
  - channel is the medium through which the signal passes.   • The noise
  - source represents the distortions and corruptions that afflict the
  - signal on its way to the receiver.  The receiver decodes the
  - message, reversing the action of the transmitter.   • The
  - destination is the recipient of the message.

The beauty of this stripped-down model is that it applies
universally. It is a story that messages cannot help but play
out—human messages, messages in circuits, messages in the neurons,
messages in the blood. You speak into a phone (source); the phone
encodes the sound pressure of your voice into an electrical signal
(transmitter); the signal passes into a wire (channel); a signal in a
nearby wire interferes with it (noise); the signal is decoded back
into sound (receiver); the sound reaches the ear at the other end
(destination).

In one of your cells, a strand of your DNA contains the instructions
to build a protein (source); the instructions are encoded in a strand
of messenger RNA (transmitter); the messenger RNA carries the code to
your cell’s sites of protein synthesis (channel); one of the “letters”
in the RNA code is randomly switched in a “point mutation” (noise);
each three-“letter” code is translated into an amino acid, protein’s
building block (receiver); the amino acids are bound into a protein
chain, and the DNA’s instructions have been carried out (destination).

Those six boxes are flexible enough to apply even to the messages the
world had not yet conceived of—messages for which Shannon was, here,
preparing the way. They encompass human voices as electromagnetic
waves that bounce off satellites and the ceaseless digital churn of
the Internet. They pertain just as well to the codes written into
DNA. Although the molecule’s discovery was still five years in the
future, Shannon was arguably the first to conceive of our genes as
information bearers, an imaginative leap that erased the border
between mechanical, electronic, and biological messages.

 -- [[http://nautil.us/issue/51/limits/how-information-got-re_invented][How Claude Shannon Rebooted Information]] | Nautilus
    [[bib:soni:2017mind][A Mind at Play]] |  Jimmy Soni & Rob Goodman (2017)
#+end_quote

