#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Why?
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-why.org
  :Created: 2017-03-07T10:29@Prek Leap (11.642600N-104.919210W)
  :ID: 5503d519-23e7-4d5e-9a86-99f6bf310424
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

I don't believe that this belongs in the prolog.  The reasons for
building a distributed civilization and spreading that civilization
throughout the solar system is self-evident.  The reasons people give
against it goes against every fucking gene on our dna that make us
what we are, and have enabled the cozy comfortable lives that give
people the free time to look at endless cat pictures on Facebook.  And
when I say cozy I'm not talking about the rich middle classes in
developed countries, but even the people on the lower level of
[[https://en.wikipedia.org/wiki/Maslow%27s_hierarchy_of_needs][Maslow's hierarchy of needs]] who have 3G and access to potable water, and food
every day.  Compared to our ancestors living on the savannah, with few
tools and no fire, yes, even a favela[fn:2] in the dingy part of Phnom
Penh is pretty cozy.

   [ rant continues more a bit ]



Why are people so scared of exploration today?  I don't understand --
when the world was much bigger than it is today, and there were still
large forgotten swaths of the earth that hadn't been explored in many
millennia[fn:1], such expeditions were celebrated as being one of the most
noble of pursuits that one could pursue.

Now climbing Everest or reaching the South Pole are just items on
bucket lists and called /extreme sports/.

People scream bloody murder when spending even a tiny fraction of what
is spent every year on arms, the military and surveillance.  In 2014
Americans spent [[http://www.cbsnews.com/news/americans-spent-a-record-56-billion-on-pets-last-year/][$56 billion]] on pets.  In the same year the Defense
budget was $3.64 Trillion.  Compare that to and NASA's budget was a
little over $17 billion, less than a third of what was spent on cats,
dogs and the odd goldfish or turtle.



The argument I will make is that our species has only one way forward
-- into and throughout the solar system or perish.  Mankind has never
solved it's problems by staying home.  We tend to turn petty and short
cited and squabble all the while fouling our bed.  In one respect, the
image of Mankind polluting the entire solar system is distressing.
It's not some noble pursuit, it's not in search of a Utopia, and it's
not turning our backs on Earth -- far from it.  In fact this is the
only way we can redeem our wretched behavior on this planet.

Europeans left the Old World to establish themselves in the so called
New World, which was certainly not new to the inhabitants that they
displaced.  The Old World's carrying capacity was straining under the
population, and there certainly wasn't much pleasant in the great
cities of London or Paris -- they were fetid caldrons of filth,
disease with a high incendinary index -- which is finally what cleaned
them out.  But as European civilization established itself on the
bones of two continents that had been all but wiped out by small pox
in the Americas and inflicted


** Against

The old argument that we as a civilization should concentrate on
spending resources to solve problems here on earth than to do things
like human exploration and colonization.

  - 
  - [[https://aeon.co/essays/is-a-mission-to-mars-morally-defensible-given-todays-real-needs][Is a mission to Mars morally defensible given today’s real needs?]] | Aeon Essays
  - [[https://qz.com/907211/should-we-live-on-mars-nasa-astronaut-ron-garan-believes-we-should-focus-on-fixing-problems-on-earth-instead-of-martian-colonization/][Should we live on Mars?]] | Quartz
  - [[http://www.foresight.org/nano/Mars.html][Space Development: The Case Against Mars]] | Eric Drexler
  - [[https://e4a-net.org/2017/01/24/why-were-not-going-to-mars-by-timothy-crownshaw/][Why we’re not going to Mars]] | Timothy Crownshaw – Economics for the Anthropocene

** For

#+begin_quote
  Look again at that dot. That's here. That's home. That's us. On
  it everyone you love, everyone you know, everyone you ever heard
  of, every human being who ever was, lived out their lives. The
  aggregate of our joy and suffering, thousands of confident
  religions, ideologies, and economic doctrines, every hunter and
  forager, every hero and coward, every creator and destroyer of
  civilization, every king and peasant, every young couple in love,
  every mother and father, hopeful child, inventor and explorer,
  every teacher of morals, every corrupt politician,
  every "superstar," every "supreme leader," every saint and sinner
  in the history of our species lived there--on a mote of dust
  suspended in a sunbeam.

  The Earth is a very small stage in a vast cosmic arena. Think of
  the rivers of blood spilled by all those generals and emperors so
  that, in glory and triumph, they could become the momentary
  masters of a fraction of a dot. Think of the endless cruelties
  visited by the inhabitants of one corner of this pixel on the
  scarcely distinguishable inhabitants of some other corner, how
  frequent their misunderstandings, how eager they are to kill one
  another, how fervent their hatreds.

  Our posturings, our imagined self-importance, the delusion that
  we have some privileged position in the Universe, are challenged
  by this point of pale light. Our planet is a lonely speck in the
  great enveloping cosmic dark. In our obscurity, in all this
  vastness, there is no hint that help will come from elsewhere to
  save us from ourselves.

  The Earth is the only world known so far to harbor life. There is
  nowhere else, at least in the near future, to which our species
  could migrate. Visit, yes. Settle, not yet. Like it or not, for
  the moment the Earth is where we make our stand.

  It has been said that astronomy is a humbling and
  character-building experience. There is perhaps no better
  demonstration of the folly of human conceits than this distant
  image of our tiny world. To me, it underscores our responsibility
  to deal more kindly with one another, and to preserve and cherish
  the pale blue dot, the only home we've ever known.

  -- Carl Sagan, Pale Blue Dot, 1994
#+end_quote


  - [[https://www.youtube.com/watch?v=ffUnNaQTfZE&t=1030][Supertasks]] | YouTube
  - [[https://www.youtube.com/watch?v=YH3c1QZzRK4][Wanderers]]  | YouTube
  - [[https://en.wikipedia.org/wiki/Pale_Blue_Dot][Pale Blue Dot]]  | Wikipedia
  - [[http://www.planetary.org/explore/space-topics/earth/pale-blue-dot.html][A Pale Blue Dot]] | The Planetary Society
  - [[https://www.youtube.com/watch?v=p86BPM1GV8M][Pale Blue Dot]] | YouTube
  - [[http://www.teslarati.com/yes-deserve-colonize-mars-keep-light-consciousness/][Yes, we deserve to colonize Mars and keep our “light of
    consciousness”]] | Teslarati
  - [[https://launiusr.wordpress.com/2012/02/08/why-explore-space-a-1970-letter-to-a-nun-in-africa/][Why Explore Space? A 1970 Letter to a Nun in Africa]] 

*** Carl Sagan Tribute Series

[[http://www.industrytap.com/wanderers-tormented-everlasting-itch-things-remote/24997][Wanderers Tormented with an Everlasting Itch for Things Remote]] | Industry Tap

- i [[https://www.youtube.com/watch?v=Qfm0GCvsIVA][  A Universe Not Made For Us]] | YouTube
- ii  [[https://www.youtube.com/watch?v=E6kStH-LXgI][Consider Again That Pale Blue Dot]] | YouTube
- iii [[https://www.youtube.com/watch?v=sKtHR1eUubI][Wanderers]] | YouTube


* Explorer Quotes

#+begin_comment
all of these quotes were from Pale Blue Dot pg213  Need to
track them down independently.
#+end_comment

#+begin_quote
I ... had ambition not only to go farther than anyone had
done before, but as far as it was possible for man to go.

-- Captain James Cook
#+end_quote

#+begin_quote
The Cosmos is a magnet ... Once you've been there, all you
can think of is how to get back.

-- Yuri Romanenko
#+end_quote

#+begin_quote
The future posibilities of space-travel, which are now left
mainly to unfound fantasy, could be more soberly treated
without ceasing to be interesting and could show to even the
most adventurous of the youn that a world without way need
not be a world without adventures and hazardous glory.  To
this kind of contest there is no limit.  Each victory is
only a prelude to another, an no boundries can be set to
rational hope.

-- Bertrand Russell | 1959
#+end_quote

#+begin_quote
It seemed to have Lord Infante that if he or some other lord
did not endevor to gain that knowledge, no mariners nor
merchants would ever dar to attempt it, for it is clear that
none of them ever trouble themselves to sail to a place
where there is not a sure and certain hope of profit.

-- Gome Eanes de Zurara quoting Prince Henry the Navigator
#+end_quote

When Sagan quoted Prince Henry in Pale Blue Dot, SpaceX was
nowhere near the horizon.  Not surprisingly, Sagan saw space
exploration as only within the realm of the Nation State or
multiple Nation States in partnership.

The idea of rockets that could be reused much the same as a
747, which takes off, lands, is refueled and takes off again
was not really on anyone's radar.

* Dead-end Arguments

Sagan does a brilliant job of going through all of the
traditional justifications for Nation-States spending large
amounts of money on manned space-exploration.

  - spinoffs



They didn't hold up then and they don't hold up now except
that the profit motive will justify the expense, but not
within today's very short investment time frames.  We will
come back to that later.


* Extreme Risk Adversion

In the recent National Geographic Mini-Series, Mars, the big
existential crises for the nascent colony was when a
scientist, having become delusional after prolonged power
shortages killed off all of the botanical experiments, and
depressurized a compartment resulting in the death of
several people.  This triggered a backlash back on earth
that nearly caused the expedition to be canceled, with the
understanding that if it was canceled, it would be unlikely
man would ever return to Mars in the forseeable future.

This is the problem when too few eggs are placed in a single
basket.  If there are a lot of eggs in a single basket and a
few eggs are lost, it is acceptable, but if a single egg is
lost of only a handful, we tend to see it as a disaster and
tragedy.  This is made worse the more immediate the death.
Before photos, video and the global internet brought
everything into everyone's homes in real time, most events,
even large scale horrific events took hours, days, weeks or
months to make it back home.  For American's, World War II
was largely at arm's length with events being reported on
the radio sometimes as quickly as within hours but
photographs, and video would take days and even weeks and by
the time it had made it past the censors and other
institutional filters, what the public did see was very low
in bandwidth and short on detail.

In this sense the Mini-Series scenario is all too plausible,
people from developed economies have lost the ability to
place risk and loss into perspective.  This is now hard wired
into several generations of people and won't change
significantly for several more generations when hopefully
people will learn to adjust to the flood of real-time
information and risk-aversion will be back in it's proper
perspective.

So the only way to make this happen will be if a large
number of people are sent, so that when people do die, and
there will be a lot of accidents, and disasters in the early
days of exploration and the establishment of permanent
settlements, that they are tragic, but not existential
threats to manned space exploration.


* Isabella Argument

#+begin_comment
From: NOTES <2015-11-20 Fri 10:41> It's THE Adventure
#+end_comment

Back in the 1970's I remember reading, in the introduction
to a collection of Science Fiction short stories that I can
not locate, an interesting analogy and argument for space
exploration, or for any /moonshot/ or big long term or large
scale undertaking.

He talked of Isabella of Spain and Christopher Columbus.  At
the time, it was universally acknowledged that who ever
could find a short-cut for trading with India that could
bipass the middlemen that took their cut on the trading
routes between India and Europe, would be insanely rich.

Columbus was a known crackpot.  His math was unsound and his
theories were barking mad.  But when he approached Isabella
for the venture capital he needed to fund his voyage, she
did a quick cost-risk analysis and understood two things.
First, the amount of money Columbus was asking for was
nothing for her.  The amount she spent, supposedly by
selling some jewels, was about the same as the cost of a
weekend party.

And even though Columbus was an obvious nut, in the extreme
unlikely chance that he succeeded to find a new route to
India, the rewards would be fantastic.  And the whole thing,
funding an exploration into the unknown, was a bit of an
adventure.  So putting it all together, the chances were
low, but the cost was cheap and it was all in all something
fun to do.

This is a good way of approaching very long term projects.
The cost, at any given time, is actually very cheap, since
costs are spread over very long time frames.  And the
chances of success are very low as well.  But if, in the
unlikely event, as did Columbus, that the project was
successful, the payoff would be enormous.

This is one way that we would like to frame our work.
Making human civilization into a distributed, federated,
multi-planet civilization will take a long time.  At least
in the early stages, the costs are very low, and the
likelyhood of success (surviving planet killers, super
volcanos, pandemics or gray goo) is very small.  But if we
do succeed the payoff is enormous -- we survive.  And the
whole project is an adventure of sorts, but not in the same
way as Isabella.

* Bread Cast Upon The Waters

#+begin_comment
From : BLOG <2010-09-26 Sun 10:45> Casting Bread Upon the Waters
#+end_comment

I have been thinking a great deal about how to build
organizations and institutions which can survive very long
periods of time.  But how do you justify such investments,
especially to a generation that measures time in nano-seconds
and measures success by the ROI in the next financial
quarter?

In a fairly recent SALT (Seminars About Longterm Thinking)
by the Long Now Foundation entitled [[http://www.longnow.org/seminars/02010/feb/01/long-finance-enduring-value-conference/][Long Finance]], Stewart
Brand read out an extended quote from [[http://en.wikipedia.org/wiki/Robert_A._Heinlein][Robert Heinlein]]'s 
[[http://en.wikipedia.org/wiki/Time_for_the_Stars][Time for the Stars]].

In the book, the *Long Range Foundation* take on very long
term goals which require such vast amounts of both time and
money that from a near-term perspective they are pointless
wastes of money.

#+begin_quote
We got interested in the purposes of the Long Range
Foundation. Its coat of arms reads: "Bread Cast Upon the
Waters," and its charter is headed: "Dedicated to the
Welfare of Our Descendants." The charter goes on with a lot
of lawyers' fog but the way the directors have interpreted
it has been to spend money only on things that no government
and no other corporation would touch. It wasn't enough for a
proposed project to be interesting to science or socially
desirable; it also had to be so horribly expensive that no
one else would touch it and the prospective results had to
lie so far in the future that it could not be justified to
taxpayers or shareholders. To make the LRF directors light
up with enthusiasm you had to suggest something that cost a
billion or more and probably wouldn't show results for ten
generations, if ever...something like how to control the
weather (they're working on that) or where does your lap go
when you stand up.

The funny thing is that bread cast upon waters does come
back seven hundred fold; the most preposterous projects made
the LRF embarrassing amounts of money -- "embarrassing" to a
non-profit corporation that is. Take space travel: it seemed
tailor-made, back a couple of hundred years ago, for LRF,
since it was fantastically expensive and offered no probable
results comparable with the investment: There was a time
when governments did some work on it for military reasons,
but the Concord of Bayreuth in 1980 put a stop even to that.

So the Long Range Foundation stepped in and happily began
wasting money. It came at a time when the corporation
unfortunately had made a few billions on the Thompson
mass-converter when they had expected to spend at least a
century on pure research; since they could not declare a
dividend (no stockholders), they had to get rid of the money
somehow and space travel looked like a rat hole to pour it
down.

Even the kids know what happened to that: Ortega's torch
made space travel inside the solar system cheap, fast, and
easy, and the one-way energy screen made colonization
practical and profitable; the LRF could not unload fast
enough to keep from making lots more money.
#+end_quote

The *Long Range Foundation* projects echos a number of
themes found in the [[http://en.wikipedia.org/wiki/The_Report_from_Iron_Mountain][Report From Iron Mountain]] ([[http://www.theforbiddenknowledge.com/hardtruth/iron_mountain_full.htm][full text of
the book]]); a hoax or satire (take your pick) published in
1966 by the Dial Press which claimed to be a leaked
government report from a government think tank exploring the
consequences of long term peace.

I was given a copy of the book around 1978 during a lazy
summer in a century old Pennsylvania farmhouse by the wife
of a retired vice-president of Harvard University turned
gentleman farmer.  The ideas explored in the book stuck in
my head, unresolved, ever since.

Philip Coppens wrote a excellent [[http://www.philipcoppens.com/ironmountain.html][article]] on *The Report From
Iron Mountain*:

#+begin_quote
Lewin proposed that until substitutes for war were
developed, “war” needed to be maintained, if not improved in
effectiveness. Part of the “genius” of Lewin is in the type
of proposed potential substitutes he proposed – some of
which may have given various governments some inspiration…
or is it just coincidence that “reality” mimics fiction? The
Report’s recommendations were:

   - a giant space-research programme whose goal was largely
     impossible to achieve (a black hole, budget-wise and
     hence able to feed the economy);
   - create a new, non-human enemy, e.g. the potential
     threat of an extra-terrestrial civilisation
   - create a new threat to Mankind, e.g. pollution
   - new ways of limiting births, e.g. via adding drugs to
     food or water supply
   - create fictitious alternate enemies
   - create an omnipresent, virtually omnipotent
     international police force.
#+end_quote

Many of these proposals should feel uncomfortably familiar.
When the cold war ended, new phantom enemies were erected
including the /War on Drugs/ and the /War on Terror/.  These
were not real Wars.  They had no concrete objectives and no
means of ever being concluded.  But so long as they could be
used to create fear, they justified the existence of the
Nation State and the vast sums of money being thrown away to
fight them.

The Nation State, as we've known since [[http://en.wikipedia.org/wiki/Peace_of_Westphalia][Peace of Westphalia]],
is on it's way out.  Finance, Transportation, Energy and
Communications are now global distributed networks which
transcend the ability of any one Nation State to control.
Pretty much all services that Nation States provide can be
delivered by either local government or the private sector.
Over the next decades all that the Nation State will have
left to offer their citizens is the threat of physical
force and the military industrial complex that Eisenhower
warned of in his [[http://en.wikisource.org/wiki/Eisenhower's_farewell_address][farewell address]] in January 1961:

#+begin_quote
Until the latest of our world conflicts, the United States
had no armaments industry. American makers of plowshares
could, with time and as required, make swords as well. But
now we can no longer risk emergency improvisation of
national defense. We have been compelled to create a
permanent armaments industry of vast proportions. Added to
this, three and a half million men and women are directly
engaged in the defense establishment. We annually spend on
military security alone more than the net income of all
United States corporations.

Now this conjunction of an immense military establishment
and a large arms industry is new in the American
experience. The total influence -- economic, political, even
spiritual --is felt in every city, every Statehouse, every
office of the Federal government. We recognize the
imperative need for this development. Yet we must not fail
to comprehend its grave implications. Our toil, resources,
and livelihood are all involved. So is the very structure of
our society.
 
In the councils of government, we must guard against the
acquisition of unwarranted influence, whether sought or
unsought, by the military-industrial complex. The potential
for the disastrous rise of misplaced power exists and will
persist. We must never let the weight of this combination
endanger our liberties or democratic processes. We should
take nothing for granted. Only an alert and knowledgeable
citizenry can compel the proper meshing of the huge
industrial and military machinery of defense with our
peaceful methods and goals, so that security and liberty may
prosper together.
#+end_quote

The purpose of the *Long Range Foundation* seems, on the
surface, to be much the same as Lewin's proposals to dump
huge amounts of money into projects which will have no
practical return on investment.  But in fact, as Heinlein
points out, the ROI from such projects is potentially
enormous.  Where war truly is a means of throwing away
money, big projects seeking to solve big ideas will often
lead to very substantial payoffs.  Just not for the
generation which initiates them.

This is a message that needs to be relearned.  We need to
make the distinction between investment whose only purpose
is to prop up power structures that are reaching the end of
their shelf life and big investments in the future that have
a real payoff.  This could form the foundation for a 
Nation State which is not based on fear and phantom enemies.

Some things take time.  Sometimes a very long time.  But the
potential payoff that your grandchildren or perhaps great
great great grandchildren will see is very real.  And it is
our responsibility to lay the groundwork for those who come
after we as individuals have passed out of living memory.
Bread cast upon the waters indeed.


* Core Patterns

 - [[./prolog-cosmos.org][Cosmos]]
 - [[./prolog-process.org][Process]]
 - [[./prolog-holon.org][Holons]]
 - [[./prolog-identity.org][Identity]]
 - [[./prolog-pace.org][Pace Layers]]
 - [[./prolog-scope.org][Scope]]
 - [[./prolog-transactive.org][Transactive Nature]]

* Footnotes

[fn:2] A favela is a portuguese word for an urban area that
is predominately poor and only semi-regulated.  A favela, or
barrio is not slum, though some people confuse favela's for
slums.  But they are deperately crowded.  A favela has
electricity, running water and sewage, and there are many
permenant structures, whereas slums typically do not have
any of these things, or if they do they are disfunctional
and not maintained.

See: [[https://en.wikipedia.org/wiki/Favela][Favela]] | Wikipedia

[fn:1] Our ancestors managed to explore and settle the vast majority
of the habitable regions of the planet in ages long past when
Mammoths, Giant Sloths and the Saber Toothed Tiger roamed the
grasslands of North America and Asia.  They interbred with close
relatives, the Neandrthal and Cro Magnon.  Their astonishing
achievement is manifest in the world we live in today, though they
left little evidence of their passing except through the occasianal
burial site or artifact and the mitochondrial DNA, a record passed
from female to female throughout the generations that resides in each
one of us.

It's commonly claimed by so-called aboriginal people's from around the
world that /they/ were first.  The nomads who first explored the
planet predate any human culture by thousands of years.  They are the
ancestors of all humans who came out of Africa and spread across the
world in three successive stages.

