#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Creating a Movement
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-movement.org
  :Created: 2017-03-19T11:03@Prek Leap (11.642600N-104.919210W)
  :ID: a697ee48-a891-4ad4-9350-b2f07e054b3f
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

  - rules for radicals
  - stupid tedtalk video
  - methodist movement

* What we can learn from religion

TEDTalk: Alain de Bottom: Atheism 2.0
:url: http://www.ted.com/talks/alain_de_botton_atheism_2_0.html

Notes:

  - culture can replace religion
  - sermons -- proactive lectures
  - repetition -- without repetition, people forget
  - structure time -- calendars
  - rituals -- eg. moon festival
  - speak well 
  - physical actions back up ideas
  - art -- art for art's sake is wrong, and artists shouldn't explain
    themselves is wrong. religion uses are as a reminder what there is
    to love, fear and hate. Art should be didactic
  - religions form institutions -- bring in money, are branded,
    organized.
  - pilgramage
  - connection with something bigger than yourself


----

    - Religion for Atheists & Sacred Stacks & Anathem
    - Education -- and trivium -- learning to think first
    - catholic monastic orders are based on Epicurean
      communities.  in fact modern religion is in most
      respects providing what in ancient times, was what
      philosophy used to provide -- frameworks for living
      life.
    - liturgy --tightly choreographed ritual-agenda
    - collective meals -- the /agape feast/
    - culture of repetition
    - arrange time -- calendars of events
    - oratory --
    - physically manifest ideas -- eg. baptism
    - art must didactic -- manifest emotions, ideas and stories
    - form institutions -- collaborative, branded,
      disciplined.
    - pilgramage
    - connect to something bigger than ourselves
    - build on top of existing culture and religions --
      christmas was a pagan holiday

* Methodism

#+begin_quote
Have you ever wondered, for example, how religious movements
get started? Usually, we think of them as a product of
highly charismatic evangelists, people like the Apostle Paul
or Billy Graham or Brigham Young. But the spread of any new
and contagious ideology also has a lot to do with the
skillful use of group power. In the late eighteenth and
early nineteenth centuries, for example, the Methodist
movement became epidemic in England and North America,
tipping from 20,000 to 90,000 followers in the U.S. in the
space of five or six years in the 1780s. But Methodism’s
founder, John Wesley, was by no means the most charismatic
preacher of his era. That honor belonged to George
Whitfield, an orator of such power and charisma that, it was
said, he once charmed a five pound contribution out of
Benjamin Franklin—who was, of course, the furthest thing
from a churchgoer. Nor was Wesley a great theologian, in the
tradition of, say, John Calvin or Martin Luther. His genius
was organizational. Wesley would travel around England and
North America delivering open air sermons to thousands of
people. But he didn’t just preach. He also stayed long
enough in each town to form the most enthusiastic of his
converts into religious societies, which in turn he
subdivided into smaller classes of a dozen or so
people. Converts were required to attend weekly meetings and
to adhere to a strict code of conduct. If they failed to
live up to Methodist standards, they were expelled from the
group. This was a group, in other words, that stood for
something. Over the course of his life, Wesley traveled
ceaselessly among these groups, covering as much as four
thousand miles a year by horseback, reinforcing the tenets
of Methodist belief. He was a classic Connector. He was a
super Paul Revere. The difference is, though, that he wasn’t
one person with ties to many other people. He was one person
with ties to many groups, which is a small but critical
distinction. Wesley realized that if you wanted to bring
about a fundamental change in people’s belief and behavior,
a change that would persist and serve as an example to
others, you needed to create a community around them, where
those new beliefs could be practiced and expressed and
nurtured.

-- Malcom Gladwell | The Tipping Point
#+end_quote

- [[https://en.wikipedia.org/wiki/George_Whitefield][George Whitefield]] | Wikipedia

* Overton Window

  - [[https://en.wikipedia.org/wiki/Overton_window][Overton window]] | Wikipedia

#+begin_quote
"Many who before regarded legislation on the subject as chimerical,
will now fancy that it is only dangerous, or perhaps not more than
difficult. And so in time it will come to be looked on as among the
things possible, then among the things probable;–and so at last it
will be ranged in the list of those few measures which the country
requires as being absolutely needed. That is the way in which public
opinion is made."

"It is no loss of time," said Phineas, "to have taken the first great
step in making it."

"The first great step was taken long ago," said Mr. Monk,–"taken by
men who were looked upon as revolutionary demagogues, almost as
traitors, because they took it. But it is a great thing to take any
step that leads us onwards."

-- [[https://en.wikipedia.org/wiki/Phineas_Finn][Phineas Finn]] | [[https://en.wikipedia.org/wiki/Anthony_Trollope][Anthony Trollope]]
#+end_quote

* Creeping Normality

Creeping normality if the Overton Window's evil twin.

  - [[https://en.wikipedia.org/wiki/Creeping_normality][Creeping normality - Wikipedia]]
