#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Estranged
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-estranged.org
  :Created: 2017-03-17T18:56@Prek Leap (11.642600N-104.919210W)
  :ID: feb60ccf-5655-4bde-a853-37381f808026
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>


* A Cautionary Preface

#+begin_quote
If you are interested in stories with happy endings, you would be
better off reading some other book. In this book, not only is there no
happy ending, there is no happy beginning and very few happy things in
the middle.

-- Lemony Snicket, The Bad Beginning
#+end_quote

There is always a danger in any premise that begins with denouncing
the present and offering some (insert your favorite adjective here:
noble, heroic, pastorial, gentle, harmonious, wise..) romanticized and
dry-cleaned picture of how the past was better.  There are /so/ many
ways this is wrong that it would require a multi-volume work to even
give an adequate summary of how wrong it is.

Every present in every past age has enormous problems, and every
present in every age to come in the future will well.  That's just the
way it is.  However, in most cases, it's not all bad.  There are some
things which, seemingly by accident, every age has gotten right.
Sadly it's usually the case that whenever we get something right, it
never lasts and we manage to screw it up for the next generation, who
look back nostalgically at that those few things that were better in
the past which no longer work in the present.

It is also true that none of the good things in the past, present or
future emerged whole an perfect like Venus from the sea-foam[fn:1].
The good evolved by trial and error, with many false starts, and many
imperfect iterations before it first, didn't suck, and then was okay
before (long after that process had been forgotten) it became good.
And it was good for a while, and then it wasn't.  And after it was no
longer good, it became reviled, and the memory of when it was good
romanticized.

Some of the good stuff has survived, preserved because people have
seen value in it, be it beauty, utility or intrinsic monetary value.
We look to these artifacts from the past mostly in the form of art and
architecture as a sign that the past is worth remembering, both the
good and the bad as well.

The dreary monotonous horrors that were part of everyone's day to day
existence were so pervassive that no one thought to leave a record of
them unless they had grown into a plague or precipitated a collapse.

There never was, can or could have or be a garden of paradise.
Innocence, perfection or purity of mind and body are little more than
fleeting moments, snapshots frozen in time, out of context that don't
include the becoming that came before, or the becoming of what they
turn into later.  The six year old, knelling before bed with hands
clasped, eyes shut in fervent prayer that "the puppy will stay a puppy
forever" is never far from our hearts and prayers.  That the perfect
seaside holiday with friends could go on forever and no one would have
to go home, or go back to school or work, or be subjected to the
mindless pointlessness of the process of maintanence, which is 90% of
everything. Though even the six year old, knows in her own way, that
her wish can never be granted.




* Introduction

#+begin_quote
Man is estranged from that with which he is most familiar.

-- Hericlitus, quoted by Charles Olson.
#+end_quote




* Seeing like a State

 - [[https://slatestarcodex.com/2017/03/16/book-review-seeing-like-a-state/][Book Review: Seeing Like A State]] | Slate Star Codex
 - [[bib:scott:1999state][Seeing Like a State]] | James Scott


Christopher Alexander dedicated his life's work to healing this
estrangement but he was never very good at articulating it.  You could
almost viscerally feel Alexander's anguish bleeding from every
character of every page of every book he wrote.  But what had happened
to the modern world was so at odds with every fiber of his being that
perhaps it was beyond him to understand why and how it happened.

In a sense, the following quote encapsulates the estrangement
perfectly:

#+begin_quote
Scott starts with the story of “scientific forestry” in 18th century
Prussia. Enlightenment rationalists noticed that peasants were just
cutting down whatever trees happened to grow in the forests, like a
chump. They came up with a better idea: clear all the forests and
replace them by planting identical copies of Norway spruce (the
highest-lumber-yield-per-unit-time tree) in an evenly-spaced
rectangular grid. Then you could just walk in with an axe one day and
chop down like a zillion trees an hour and have more timber than you
could possibly ever want.

This went poorly. The impoverished ecosystem couldn’t support the game
animals and medicinal herbs that sustained the surrounding peasant
villages, and they suffered an economic collapse. The endless rows of
identical trees were a perfect breeding ground for plant diseases and
forest fires. And the complex ecological processes that sustained the
soil stopped working, so after a generation the Norway spruces grew
stunted and malnourished. Yet for some reason, everyone involved got
promoted, and “scientific forestry” spread across Europe and the
world.

-- Scott Alexander | Review of Seeing Like a State
#+end_quote


In effect, it was rationalism and the scientific method run amok, that
turned modernism into the monster it became.  But it wasn't
rationalism or the scientific method per se, but man's tendency to
never do anything in half measures -- if one spoon of sugar in one's
coffee was good, then a cup or two of sugar must be better!  We're
like Malcom[fn:2] who we had just watched jump off the roof of his
house on a dare from his brother, his older self, narrating the voice
over saying "it seemed like a good idea at the time..."

Treebeard[fn:3] was right in calling Man a 'hasty folk'.  We're all too
wrapped up in the moment to think things through and become
righteously indignant when it is pointed out and rather than modify
our behavior we double-down and make things worse with a wave of a
hand, a denial, a justification.

In another sense, it's a bit like the ancient saying that when your
only tool is a hammer, everything begins to look like a nail.  And by
extension, the Japanese proverb, nail that sticks out gets hammered
down.  We know our own shortcomings, but can be relied on not to
overcome them time and time again.
U



* Footnotes

[fn:1] I never understood the sea-shell thing, used in numerous
depictions, most famously Botticelli but also in painting unearthed in
Pompeii....

[fn:3] [[https://en.wikipedia.org/wiki/Treebeard][Treebeard]], the eldest living Ent.  Ent's were long lived
(living up to tens of thousands of years) tree-like race who were the
'Shepherds of the Forest' or 'Tree-Herders' in Tolkien's fictional
Middle Earth.

[fn:2]  A character in the American TV sitcom [[https://en.wikipedia.org/wiki/Malcolm_in_the_Middle][Malcolm in the Middle]]
2000-2006.


