#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Foragers and Farmers
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/prolog-forage-farmer.org
:Created:   2017-09-04T17:58@Prek Leap (11.642600N-104.919210W)
:ID:        d18586e4-4e01-43b0-9d4e-c875c24ae012
:VER:       557794788.792619981
:GEO:       48P-491193-1287029-15
:BXID:      proj:QCU1-0286
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

Robin Hanson, Scott Alexander etal


  - [[http://www.overcomingbias.com/2017/08/forager-v-farmer-elaborated.html][Forager v Farmer, Elaborated]] | Overcoming Bias
  - [[http://www.overcomingbias.com/2015/08/specific-vs-general-foragers-farmers.html][Specific vs. General Foragers & Farmers]] | Overcoming Bias
  - [[http://www.overcomingbias.com/2010/10/two-types-of-people.html][Two Types of People]] | Overcoming Bias
  - [[http://www.overcomingbias.com/2010/10/fear-made-farmers.html][Fear Made Farmers]] | Overcoming Bias
  - [[http://slatestarcodex.com/2013/03/04/a-thrivesurvive-theory-of-the-political-spectrum/][A Thrive/Survive Theory Of The Political Spectrum]] | Slate Star Codex
  - [[http://www.overcomingbias.com/2016/04/school-is-to-submit.html][School Is To Submit]] | Overcoming Bias
  - [[http://www.overcomingbias.com/2012/07/the-riddle-of-ritual.html][The Riddle of Ritual]] | Overcoming Bias
  - [[http://www.econ.yale.edu/smith/econ116a/keynes1.pdf][Economic Possibilities for our Grandchildren]] (pdf) | John
    Maynard Keynes, 1930
  - [[http://www.overcomingbias.com/2010/06/foragers.html][Foragers]] | Overcoming Bias
  - [[http://mason.gmu.edu/~rhanson/forager.pdf][Forager Facts]] | Youngberg, 2010
  - [[http://www.overcomingbias.com/2012/08/sex-at-dusk-v-sex-at-dawn.html][Sex At Dusk v. Dawn]] |  Overcoming Bias

  -  

----

Should start with concept of Hobbes vs Rousseau's /Nobile
Savage/ and misconceptions about man, violence and war....

 - War Before Civilization | Keeley, 1996
 - Constant Battles | LeBanc, 2003
 - War in Human Civilization | Gat, 2006 
 - The World Until Yesterday | Diamond, 2012 

----

The general idea is that the people settled down during the
agricultural revolution a new way of thinking was required.  

#+begin_quote
Farming required huge behavior changes, mostly unnatural to
foragers. A key enabler seems to have been increased
self-control to follow social norms. But what allowed this
increased self-control?

-- [[http://www.overcomingbias.com/2010/10/fear-made-farmers.html][Fear Made Farmers]] | Overcoming Bias
#+end_quote


Farming is all about land, and possession of land, which is
why we use property to mean both land and any goods that you
possess.  A farmer invests a great deal of time and effort
into their farm, and if someone takes that away, it is a
great loss for the farmer because it's not easy to move
somewhere else, find land that no one is using and then
start from scratch.  So fear of loosing land is at the heart
of farming.  Women and children were tied up with property
as well because children would get your property after your
death, it was important to be very clear whose children your
wife bore.  Defense of property required large strong men
who could fight.

Farmers are not exactly ideal warriors, so farmers would
band together into groups and pay for protection from
strongmen, warlords, and later kings and even later, states.
Because the warrior class was under the control of the king
or state, and that they had a monopoly on use of force, they
eventually took over and farmers became subject to the
warrior class.  Religions changed from being animistic, to
being anthropomorphic personified dieties who ruled mankind
the way the kings rules the farmers.  But these new gods
were always angry at people when they disobeyed or broke the
rules.  At the root of all of this was the threat of death
by the gods, or more likely by the followers of the gods who
would punish you on their behalf.

#+begin_quote
One source was moving from vague spirituality to religions
with powerful and morally-outraged gods who punish norm
violators. In addition (as I’ll explain tomorrow), high
densities and larger social networks made stronger credible
threats to ostracize folks for specific deviant acts.  Yes
both these mechanisms require the fear that norm violations
could lead to great harm, even death. But for poor farmers
living on edge, such threats were easy to come by.

Interestingly, this death-threat pressure could work even
without farmers being conscious of the relevant threats or
fears. In fact, farming society probably worked better with
homo hypocritus farmers, consciously denying that strong
social pressures pushed them to do what would otherwise feel
unnatural.

-- [[http://www.overcomingbias.com/2010/10/fear-made-farmers.html][Fear Made Farmers]] | Overcoming Bias
#+end_quote

Belief in these systems became the bedrock of the system.
Money was invented as a intermediate token system for
trading goods in markets of people who you may or may not
know.  Because of the flexibility of money, it became as
important as land, and people were scared to loose it or
have it taken away because it's loss would hurt them.  So
kings and states, ended up issuing money, and backing it up
with the warrior class.  But in the end, the whole system is
built on fear used to keep people in their place and force
them to do what the more powerful wanted.


....

Foragers don't have this problem.  They could move any time.
So if there are places where they can go to forage, it
doesn't matter if they find other people foraging where they
had been before.  Foraging bands have often had friendly
relationships with neighboring bands, so long as there was
enough resources to support all bands.  Possessions were
limited because they had to be carried from place to place,
so there wasn't an investment in land and possessions that
would hurt them if they were lost.  Bands were larger than a
family, and it was likely that partnering was a bit more
looser than for farmers.


So how does this square with Keeley, LeBlanc and Diamond?

Is slash/burning agriculture or foraging?  are forrest
peoples different from savannah?

So, does the theory that foragers were less war-like and
violent hold up?  The thing is that we don't have a lot of
data on real foragers, /forager facts/ only has data from a
handful of groups and all from the late 19th century and
even then it was difficult to find data on groups that
hadn't been influenced by modernity.

....

#+begin_quote
The farming mode required humans to swallow many changes
that didn’t feel nice or natural to foragers. While foragers
are fiercely egalitarian, farmers are dominated by kings and
generals, and have unequal property and classes. Farmers
work more hours at less mentally challenging tasks, and get
less variety via travel. Huge new cultural pressures, such
as religions with moralizing gods, were needed to turn
foragers into farmers.

-- [[http://www.overcomingbias.com/2016/04/school-is-to-submit.html][School Is To Submit]] | Robin Hanson, Overcoming Bias, 2016
#+end_quote

The agricultural revolution laid the psychological
groundwork for preparing people for the industrial
revolution.  But strangely, the trend since the late 20th
century if for people to tend turn their backs on the
farmer/worker model and begin to act more like foragers.

#+begin_quote
In the absence of such threats, the talky collective was the
main arena that mattered. Everyone worked hard to look good
by the far-view idealistic and empathy-based norms usually
favored in collective views. They behaved well when
observed, learned to talk persuasively to the group, and
made sure to have friends to watch and talk for them. They
expressed their emotions, and acted like they cared about
others.

When they felt on good terms with the group, people could
relax and feel safe. They then become more playful, and
acted like animals generally do when playful. Within a
bounded safe space, behavior becomes more varied, stylized,
artistic, humorous, teasing, self-indulgent, and emotionally
expressive. For example, there is more, and more varied,
music and dance. New possibilities are explored.

A feeling of safety includes feeling safe to form more
distinct subgroups, without others seeing such subgroups as
threatening factions. And that includes feeling safe to form
groups that tend to argue together for similar positions
within talky collective discussions, and to disagree with
the larger group. After all, it is hard for a talky
collective to function well unless members are allowed to
openly disagree with one another.

But when the group was stressed and threatened by
dominators, outsiders, or famine, the collective view
mattered less, and people reverted to more general
Machiavellian social strategies. Then it mattered more who
had what physical resources and strength, and what personal
allies. People leaned toward projecting toughness instead of
empathy. And they demanded stronger signals of loyalty, such
as conformity, and were more willing to suspect people of
disloyalty. Subgroups and non-conformity became more
suspect, including subgroups that consistently argued
together for unpopular positions.

-- [[http://www.overcomingbias.com/2017/08/forager-v-farmer-elaborated.html][Forager v Farmer, Elaborated]] | Overcoming Bias, 2017
#+end_quote

Is it really safety vs fear that divides forager from farmer
or a present vs future (okay, these are connected).
Foragers lived from day to day, farmers lived for tomorrow:

Sapiens quote

#+begin_quote
Many anthropological and archaeological studies indicate
that in simple agricultural societies with no political
frameworks beyond village and tribe, human violence was
responsible for about 15 per cent of deaths, including 25
per cent of male deaths. In contemporary New Guinea,
violence accounts for 30 per cent of male deaths in one
agricultural tribal society, the Dani, and 35 per cent in
another, the Enga. In Ecuador, perhaps 50 per cent of adult
Waoranis meet a violent death at the hands of another human!

-- Sapiens 
#+end_quote

Gat, /War in Human Civilization/, 130–1;
 
Robert S. Walker and Drew H. Bailey, /Body Counts in Lowland
South American Violence/, Evolution and Human Behavior 34
(2013), 29–34.

