#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Minimum & Maximum Viability
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-viability.org
  :Created: 2017-04-16T19:21@Prek Leap (11.642600N-104.919210W)
  :ID: 44a4538c-72b0-4ff3-a919-c75c1e67f08b
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Once we have accepted the wisdom of the LOCKSS model and that this
provides Mankind with it's best chance of maximizing it's long term
survival and sustained level of properity we face the rather daunting
task of determining what is the minimum size in terms of population,
technology, tools and skills required that constitute a sustainable
technological civilization.  That would give us a baseline for how
many instances of civilization that we can theoretically maintain
any given population.

As anyone who is familiar with maintaining computer backups, it is not
as simple a creating a bunch of copies.  There are many different
statistical models that can be used to determine how many copies can
be maintained in such a way that X number of copies can be destroyed
and still reconstitute anything that has been lost.  This means that
we don't have to use the same brute force duplication that DNA
employess to achieve the same results.  But before we can get into any
of that we need to determine a number of minimal viability parameters
that taken together constitute a sustainable civilization.

In one respect, this could be the single most important reason to go
to Mars other than Mars as a backup of Earth.  It may be impossible to
know for certain what real minimum viability is unless we can build
and demonstrate it in the real world, or at least on another, real
world like Mars.

Civilization is such a large, dynamic, complex system that it is like
the weather, the number of variables and interactions is beyond
meaningful prediction beyond very short term, and crude projects that
even then are not always accurate.

----

These thresholds include minimum viable:

  - Population :: to maintain enough genetic diversity to maintain a
                  healthy population.
  - Ecosystem  :: made up of plants, animals, micro-organisms, energy
                  and chemical processes that provide mankind with a
                  livable habitat to live in.
  - Tools & Processes :: which include the designs for tools, machines,
       vehicles and structures, together with the proscriptive
       recipes needed to use them.
  - Specializations :: that break down the different tasks and
       categories of work required to maintain a given level of
       complexity.
  - Resources   ::  energy, chemical compounds, minerals and materials
                    needed and how to produce them.
  - Communities ::  that can maintain these backups over very long
                    time frames which can then restore knowledge when
                    it has been lost.

Our goal over the next decade is to learn and develop what these
minimum viable thresholds and requirements are and to integrate them
into a body of knowledge that constitutes a backup of civilization
which will be used to establish bootstrap communities who are
responsible for maintaining these backups both here on earth and
eventually throughout the solar system.



* Minimum Viable Thresholds


- Minimum Viable Population
- Minimum Viable Biodiversity
  - wild
  - cultivated
- Minimum Viable Specialties
- Minimum Viable Toolset
- Minimum Viable Materials
  list of raw materials
- Minimum Viable Elements
  list of metals, chemicals, gases etc
- Minimum Viable Compounds
  chemical compounds

* Minimum Viable Complexity

Minimum Viable Complexity it made up of:

  - Min Viable Population (MVP)
  - Min Viable Tools (MVT)
  - Min Viable Specialties (MVS)
  - Min Viable Processes (MVP)

Start with MVP, then divide that number into backup or jumpstart
communities of 1,500 to 2,500 individuals.  At the core of those
communities will be a cloistered community at or smaller than the
Dunbar number, whose sole job is the collection, preservation, and
distribution of information, and to keep all MVS in living memory
within the community.

When at minimum, one of these communities has been established on an
planet or moon other than earth, man will have become a multi-planet
species.

These communities will also become the center of new very long term
institutions that are independent of religious or secular
organizations.  The group that controls the territory surrounding
each enclave will maintain a treaty that they will not interfere or
participate in any way, but will act as a long term repository and
information broker for that territory if they desire it.  Neutrality,
and silence will be maintained -- and the enclave will remain
isolated. 

We will establish MVC for three different levels of complexity:

  - 18th century :: peak of agracultural, mechanisms, advanced 
                    tools -- it would be cool to include bio-
                    engineered things like page trees, biolumin
                    lighting, and synthetic photosynthesis for
                    very small scale electricty,
  - 19th century :: peak of mechanical + electricity, 
                    internal combustion, thorium & hydrogen
                    power sources.
  - 21st century :: computer controlled matter fabrication
                    and compiling, robotics, DNA sequencing 
                    and manipulation, advanced networks, 
                    storage and computation, thorium & 
                    hydrogen power sources.

This will have to be done for several different climates and parts of
the world:

  - tropical
  - desert
  - temperate
  - arctic

These levels will not meant to be historically accurate, that's not
the intention.  But each of these eras represent a base-line for
complexity at different times in the past.  The goal is to achieve the
best possible quality of life for a minimum and maximum population
size at a given level of complexity.

* Minimum Viable Community

What is the minimal viable size of a community to maintain our present
civilization? 

** Minimum Genetic Pool
*** Minnumber of skill sets
*** Minumum-Maximum Environmental Range
**** Min-Max temperature range
**** Min-Max potable water
**** Min-Max sunlight
**** Min arable land
*** Minimum Biodiversity
**** Domestic
***** Min number of plants
***** Min number species
**** Wild
***** plants and animals

In the case of animals and plants in the wild, we must look at this in
terms of extinction events.  What will crash food chains and
eco-systems.

Eco-systems are a crucial part of maintaining weather cycles -- the
ecology of the planet drives a lot of weather -- 

*  Minimum Viable Population

  - [[https://en.wikipedia.org/wiki/Minimum_viable_population][Minimum viable population]] | Wikipedia


  - Minimum Viable Population :: between 50 (post Toba population) and 10,000.
  - Dunbar's Number :: 150
  - Minimum Viable Specialties :: ??

*MVP* can be hacked by storing embryos, and, or eggs and sperm, and
then use over time to increase genetic diversity in a smaller
breeding pool.

*MVS* will depend on what level of technical complexity that is to be
maintained.  This could be broken down into three levels:

  - St.Gall Level ::  The level of technology represented in the Plan
       of St. Gall, a plan for a Carolingian Monastery (9th Century CE)
  - Edwardian Farm Level :: The level of technology used to maintain a
       English farming community during the reign of King Edward
       (1901-1910CE).
  - Akibahara Level :: The level of technology represented by what
       you can buy on any given day in Akibahara, Tokyo. In other
       words, technology on the cutting edge.

It will be very interesting to see the gap between St.Gall and the
Edwardian levels -- science as we know it didn't exist in the 9th
century, and steam engines along with the myriad of steam powered
machines didn't exist either.  But there were still many aspects of
technology that would be recognizable.

* Carrying Capacity 

  - [[https://en.wikipedia.org/wiki/Carrying_capacity][Carrying capacity]] | Wikipedia

A more common term for the maximum viability of an ecosystem is of
course its /carrying capacity/.

This is certainly not limited to humans -- when locust swarm they
quickly exhaust the carrying capacity of a region which results in a
collapse and die-off of the population.

Human civilization is an almost cyclical progression of successful
populations exceeding the carrying capacity of their ecosystems, at
which time there is collapse and a die-off.

The carrying capacity is not a hard number, it depends on a number of
different parameters that can be leveraged to increase or decrease
that capacity.  


* Comparison thought experiment

When trying to work out how large a population is required
to build and maintain an advanced technological industrial
civilization we can look at various countries to today and
their population to give us an idea of an approximate floor.

What are the countries that could reasonibly be  said to
have created something close to a self-sustaining
civilization within their borders.  This is fairly easy if
you are willing to go back as far as the Edwardian Era --
which was an early industrial level of civilization.  But
once we get to the 19th century things are not so simple.

So let's just look at two -- Great Britian and Japan.

Both are large island states, with homogeneous populations
and very well established industrial economies.  As the
industrial revolution gained momentum, both countries began
to export goods and import raw materials that created
problems that led to much larger problems with the countries
they were getting their raw materials from.  But
educationally, technologically and in terms of manufacturing
they were both fairly self-sufficient both agriculturally
and industrially.


  - GB 1890  37.7M
  - JP 1890  40.2M

Musk's goal is to put a million people on Mars.  Is this
enough to build a self-sustaining civilization?

Let's first ask what the percentage of educated people there
were in the 1890's in GB and JP:

  - % of population who are educated
  - % of population making up families of educated
      including children, child rearing adults, elderly 
      and dependent non-productive people

let's now assume that all human computers and robots are
replaced by machine computers and robots and they are
collectively smart enough to be semi-autonomous to the point
where things like mines and assembly lines and much of
agriculture is largely done by robots and managed and
directed at top by humans -- so upper management are humans,
design, science, education and other kinds of innovation is
done by machine-augmented humans.

Are there then enough people to be able to create minimum
viable complexity needed to produce and manage all of the
different parts that are required?

I would say that productive to unproductive ratio will never
be less than 1 in 6.  So you'll have a productive population
of about 160,000 people at any given time that will have to
support a million, but replicate the work done (with the
help of robots) of 40 million industrial era people.

I think that 1-6 isn't right if you want a population that
is growing -- each couple needs to produce 2.x children to
keep the population from shrinking.  And we must look at
what the average lifespan is, what age do we consider to be
productive and how long will each person stay productive on
average.  Then throw in accidents, disease and people who
are never really productive -- all of those stupid cousins
add up....

What will be the ratio of productive people to robots?  That
in a sense is the real question -- how many robots do you
need to build and manage the civilization, how many robots
can be managed by a single person (averaged) and how much
innovation can augmented humans contribute to continue to
grow and solve problems and not stagnate.

Put all of this together and we have a rough idea of the IQ
and how autonomous our AI and Robots will have to be to work
within the 1 million population target.

I would also add, that as Spider Robinson observed in his
Mars Trilogy, robots are a multiplier that will allow a
small population to do things at larger scales and far
faster than we do now.

Once we arrive at these target numbers -- minimum viable
population (genetic, and breeding) for humans and all other
living things that we will put on Mars, we will need to know
the ratio of humans to robots and how high level their AI
has to be to support high ratios of humans to robots.

A washing machine has a one-to-one human-machine ratio -- it
requires one human to operate it.  But washing clothes is
not simply operating the machine.  You need to collect
clothes to be washed, sort them by different washing
methods, divide each lot into groups that will fit in the
washing machine.  Operate the machine (including feeding it
soap and softener).  Removing it from the machine and hang
to dry or place in a mechanical drier and then remove, iron
if need be, place on a hanger or fold, and then place
completed items in a drawer or wardrobe (closet).  To
automate all of this would be difficult at scale (say for
all clothes on an aircraft carrier) but becomes even more
problematic at small scales such as that of a home.

Specialized robots work well at scale.  But we will need a
solution that can do things like manage laundry.  The most
common answer to this is, to build humanoid robots that can
operate in an environment that is designed for the human
body.  But that's not how it will happen -- at least any
time soon. Robots could be designed in any number of ways
which could do all of the common tasks that humans do.  And
it's most likely that it will be swarms of robots, with each
one good at a range of tasks that can come together and so
things, and then rearrange themselves for the next task.q

----

I then want to zoom this back and see if the same can be
applied to individual Bioregions on Earth -- so that each
bio-region is mostly self-sufficient and if it has to be can
be self-sufficient long enough to restart civilization in
adjoining bio-regions.

* Job Loss From Automation

 - [[https://www.theatlantic.com/amp/article/525168/][Automation and Jobs]] | The Atlantic
 - [[http://www.oxfordmartin.ox.ac.uk/downloads/academic/The_Future_of_Employment.pdf][/Users/michaelosborne/Documents/Research/future_of_employment_paper/old/.texpadtmp/future_of_employment_18.dvi - The_Future_of_Employment.pdf]]
 - [[bib:frey:2017future][The Future of Employment: How Susceptible Are Jobs to
   Computerisation?]] | Frey (2017)

 - [[https://en.wikipedia.org/wiki/Automation][Automation]] | Wikipedia

 - [[bib:honeyman:2007child][Child Workers in England, 1780-1820]] | Katrina Honeyman
 - [[bib:lebergott:1966output][Output, Employment, and Productivity in the United States after 1800]]

This perennial hot topic that has been with us for
centuries, even before [[https://en.wikipedia.org/wiki/Ned_Ludd][Ned Ludd]] led his merry band left a
trail of wrecked weaving machinary behind them.


In the last months there have been a flurry of articles,
studies and dire predictions that over the next 10-20 years
automation will eliminate large numbers of jobs.  In "places
such as Las Vegas and the Riverside-San Bernardino area may
be the most vulnerable to automation in upcoming years, with
65 percent of jobs in Las Vegas and 63 percent of jobs in
Riverside predicted to be automatable by 2025"  The study
estimated that most urban areas will see at least 55% of
jobs being computerized.

This provides us with some concrete numbers on how many jobs
can be automated -- so if 


   These are all back of napkin figures -- In 1870 there was
   estimated to be a bit less than 12 million people in the
   UK labor market so if you have a population of about 40
   millions you get a very rough figure of 25% of the
   population working at any one time.

   So if half of those jobs were automated, you would have 5
   million workers to support 40 million with 1 person
   supporting 8 people.

   For Musk's 1 million person colony, you would have 125K
   workforce supporting a million people.  Break that into
   shops with an average size of 5 and you get 25,000 shops
   to maintain a self-supporting technological industrial
   civilization.

Is 25K highly shops with five people, lots of computational
power and robots achieve that?  There will be a lot of
redundancy involved, so if each specialty had 5 shops
filling that need you get 5 thousand different types of
shops.

* Intermittent Run Production

One important approach of getting those 25K shops to produce
everything is to realize that each shop should be able to
produce more than one specialized thing.  Generalized
short-run production can get us a long ways.  There is also
no reason why some items can't be stockpiled.  If there is
extra capacity, use it to stockpile items, say lighting
elements, or fiber, or bearings or whatever so that there
would be no need to produce those things immediately if
there is a disaster and production has to be repurposed.

In one respect this is the opposite of just-in-time... but
not... the colony is not a free market, so inventory is not
the same for them as it is for a commerical company who
stockpiles inventory in anticipation of sales.  The former
knows that the stockpile will be used, the later is tying
up captial in goods that are may or may not be sold.

The colony would treat the stores as last-in-first out and
only produce more when they are needed.

In this sense industrial production is based on competitive
production, but not one where profit is the primary goal.

