#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Windows
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/prolog-window.org
:Created:   2017-03-20T10:05@Prek Leap (11.642600N-104.919210W)
:ID:        b58326b5-3b0f-4a2f-97c2-57293ad68ec7
:VER:       551831560.449589264
:GEO:       48P-491193-1287029-15
:BXID:      proj:DFM3-0815
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* NOTE: This File is DEPRECATED 2018-04-19

Content, what little there was, has been moved to w&w www-window.org.

* Introduction

I had called this whole file the fifty-year-window, when in
fact it's not just one window -- each of items below are
different windows with very different parameters.

When you aggragate them and average them out I believe it
will be roughly 50 years -- depending on a bunch of
variables

That's why this has to be data driven more than almost any
other part of the project -- it will generate models that we
can constantly test -- generate scenarios and tweak -- it
will never end.

And as if that isn't depressing -- the window is a horizon,
that will always recede into the future just beyond our
grasp.

---

Elon Musk has said on several occasions that we have a very
short window to become a multi-planet species, if we don't
do it soon, we may never be able to do it.

  - low hanging fruit picked :: Peak Cheap Non-Renewable
       Energy, which made the industrial revolution and the
       information revolution possible -- if the present
       level of civilization collapses, these resources will
       not be available to rebuild.

  - Population Collapse :: if we fall below MV for
       technological civilization to continue to innovate at
       same level, which is needed to solve:

  - Constant Battles :: man's tendency to to self-destruct

  - Climate change   :: spend too much time on survival

We have to have our shit together within 50 years, to begin
making substantial change or we may not have the time,
resources, or number of people needed to solve the big
problems

