#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Pace Layers
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-pace.org
  :Created: 2017-02-02T18:52@Prek Leap (11.642600N-104.919210W)
  :ID: 0663fd82-9229-4376-8c78-9adb37ecc38a
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

  - Pace Layers in Brand's /Clock of the Long Now/
  - Shearing Layers in Brand's /How Buildings Learn/ 
  - Firehose --> Otium

:SEE: [[http://blog.longnow.org/02015/02/08/pace-layers-stewart-brand-paul-saffos-conversations-at-the-interval/][Pace Layer Thinkers: Stewart Brand and Paul Saffo’s Conversation at The Interval]]

#+begin_quote
the future is already here, it's just not evenly
distributed.

-- William Gibson
#+end_quote

* Issues

How to different layers communicate with each other?

Lower layers act as a brake for upper layers which don't
allow the layer above it stray too far or too fast

* Layer Models

Brand's Pacing Layers

  - fashion & art
  - commerce
  - governance
  - infrastructure
  - nature

Brand's Architectual Shearing Layers

  - stuff
  - space plan
  - services
  - skin
  - structure
  - landscape
  - site

Paul Saffo's Pacing Layers

  - Anthropos
  - Bios
  - Lithos :: literally /of stone/
  - Cosmos

People today don't understand shearing -- they think everything is
happening at the same speed -- that everything is simultaneous --
there is no separation of layers -- it's all a firehose that doesn't
give you a chance to think about the next hour, let alone tomorrow.


* Content
 - Core    :: project design, organization & management
 - Trivium :: prerequisite skills and knowledge
 - Prolog  :: discursive introduction
 - Primer  :: core code & knowledge to build and maintain civilization
   - identity :: 
   - pace     :: 
   - holon    :: 
   - scope    :: 
 - Hoard   :: recorded memory and experience
 
* Fashion & Art
 - firehose -- real-time
* Commerce
 - near real-time
----
 - kinto        :: 
 - bento        :: 

* Governance
 - collective -- asynchronous
----
Humans naturally organize themselves into:

 - states
 - nations
 - tribes
 - families & groups
 - individuals
 - roles

But today we have:

 - empires (PRC, Soviet Union) -- if an empire can stay together long
   enough it sometimes can become a nation-state.  The United States
   did it, Soviet Union fell apart before it could do it, China is
   still trying to do it.  Rome almost did it 
 - nation-states
 - regions (states)
 - areas (counties & districts)
 - settlements (cities, towns and villages)
 - neighborhoods
 - individuals

What we need to work towards is:

 - solar
 - planetary
 - bioregional
 - neighborhoods
 - families & groups 
 - individuals
 - roles

----

 - Chenla
 - b>i research group
   - b>i @prekleap  :: 
   - b>i @champasak ::  

* Infrastructure
Loosely based on TCP 7 Layer Stack

  - Application     :: Otium 
    - Interface
    - Message Layer :: message & storage
    - Transaction   :: blockchain
  - Transport       :: UDP, TCP
  - Network         :: Internet layer
  - Physical        :: ethernet, sneakernet, Token, Ring, Mesh
    - tool          :: computer, toaster, fridge, oven, aircon
    - machine       :: routers, switches, pumps, fans, motors
    - transport     :: pipes, wires, space
    - payload       :: radio, sound, microwave, light, water,
                       electricity, gas etc.
** Culture
 - philosophy :: world models (includes religion)
 - language   :: written and spoken
 - mythos     :: written and spoken
 - memory     :: collective knowledge
*** Polis      :: complex societies   10K


A civilization = cultivation + settlement


* Nature
** Anthropos  :: species             2-10M
** Bios       :: life on earth       3-4B
** Lithos     :: geological          lifetime of a solar system
** Cosmos     :: stellar             lifetime of the universe

* Quotes

#+begin_quote
Buildings rule us via their time layering at least as much as we rule
them, and in a surprising way.  The idea comes from Robert
V. O'Neill's /A Hierarchical Concept of Ecosystems/. O'Neill and his
co-authors noted that ecosystems could be better understood by
observing the rates of change of different components.  Hummingbirds
and flowers are quick, redwood trees slow, and whole redwood forests
even slower.  Most interaction is within the same pace level --
hummingbirds and flowers pay attention to each other, oblivious to
redwoods, who are oblivious to them.  Meanwhile the forest is
attentive to climate change but not to the hasty fate of individual
trees.  The insite is this: "The dynamics of the system will be
dominated by the slow components, with the rapid components simply
following along."  Slow constrains quick; slow controls quick.

-- Stewart Brand, How Buildings Learn, pg 17
#+end_quote


The full quote:

#+begin_quote
Then as =ej= approaches zero, corresponding to the fast components
approaching a kind of equilibrium with the slower dynamics, the
further dynamics of the system are dominated by the slower
components.  This is true as long as the system remains stable.

Basically the theorem demonstrates that fast components of the system
will rapidly come into balance with the slower components.
Thereafter, the dynamics of the system will be dominated by the slow
components, with the rapid components simply following along.

Translated into our hierarchical terminology, the slower components
belong to a higher level and impose contraints.  As long as the system
remains intact and stable, the next higher level determines the
overall dynamics of the system.  The lowe hierarchical level can only
operate within the contraints imposed.  Thus, constraint in a
hierarchical system is the neccessary consequence of the difference in
the race processes between levels.  The hierarchical structuring of a
dynamic system follows with mathematical neccessity from the wide
differences in rate processes.

-- Robert V. O'Neill, A Hierarchical Concept of Ecosystems. pg98-99
#+end_quote

#+begin_quote
The destiny of our species is shaped by the imperatives of survival on
six distinct time scales. To survive means to com- pete successfully
on all six time scales. But the unit of sur- vival is different at
each of the six time scales. On a time scale of years, the unit is the
individual. On a time scale of decades, the unit is the family. On a
time scale of centuries, the unit is the tribe or nation. On a time
scale of millennia, the unit is the culture. On a time scale of tens
of millennia, the unit is the species. On a time scale of eons, the
unit is the whole web of life on our planet. Every human being is the
product of adaptation to the demands of all six time scales.  That is
why conflicting loyalties are deep in our nature. In order to survive,
we have needed to be loyal to ourselves, to our families, to our
tribes, to our cultures, to our species, to our planet. If our
psychological impulses are complicated, it is because they were shaped
by complicated and conflicting demands.

-- Freeman Dyson
#+end_quote

#+begin_quote
The destiny of our species is shaped by the imperatives of survival on
six distinct time scales. To survive means to com- pete successfully
on all six time scales. But the unit of sur- vival is different at
each of the six time scales. On a time scale of years, the unit is the
individual. On a time scale of decades, the unit is the family. On a
time scale of centuries, the unit is the tribe or nation. On a time
scale of millennia, the unit is the culture. On a time scale of tens
of millennia, the unit is the species. On a time scale of eons, the
unit is the whole web of life on our planet. Every human being is the
product of adaptation to the demands of all six time scales.  That is
why conflicting loyalties are deep in our nature. In order to survive,
we have needed to be loyal to ourselves, to our families, to our
tribes, to our cultures, to our species, to our planet. If our
psychological impulses are complicated, it is because they were shaped
by complicated and conflicting demands.

-- Freeman Dyson
#+end_quote
