#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Why?
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-why.org
  :Created: 2017-03-07T10:29@Prek Leap (11.642600N-104.919210W)
  :ID: 5503d519-23e7-4d5e-9a86-99f6bf310424
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

I don't believe that this belongs in the prolog.  The reasons for
building a distributed civilization and spreading that civilization
throughout the solar system is self-evident.  The reasons people give
against it goes against every fucking gene on our dna that make us
what we are, and have enabled the cozy comfortable lives that give
people the free time to look at endless cat pictures on Facebook.  And
when I say cozy I'm not talking about the rich middle classes in
developed countries, but even the people on the lower level of
[[https://en.wikipedia.org/wiki/Maslow%27s_hierarchy_of_needs][Maslow's hierarchy of needs]] who have 3G and access to potable water, and food
every day.  Compared to our ancestors living on the savannah, with few
tools and no fire, yes, even a favela[fn:2] in the dingy part of Phnom
Penh is pretty cozy.

   [ rant continues more a bit ]



Why are people so scared of exploration today?  I don't understand --
when the world was much bigger than it is today, and there were still
large forgotten swaths of the earth that hadn't been explored in many
millennia[fn:1], such expeditions were celebrated as being one of the most
noble of pursuits that one could pursue.

Now climbing Everest or reaching the South Pole are just items on
bucket lists and called /extreme sports/.

People scream bloody murder when spending even a tiny fraction of what
is spent every year on arms, the military and surveillance.  In 2014
Americans spent [[http://www.cbsnews.com/news/americans-spent-a-record-56-billion-on-pets-last-year/][$56 billion]] on pets.  In the same year the Defense
budget was $3.64 Trillion.  Compare that to and NASA's budget was a
little over $17 billion, less than a third of what was spent on cats,
dogs and the odd goldfish or turtle.



The argument I will make is that our species has only one way forward
-- into and throughout the solar system or perish.  Mankind has never
solved it's problems by staying home.  We tend to turn petty and short
cited and squabble all the while fouling our bed.  In one respect, the
image of Mankind polluting the entire solar system is distressing.
It's not some noble pursuit, it's not in search of a Utopia, and it's
not turning our backs on Earth -- far from it.  In fact this is the
only way we can redeem our wretched behavior on this planet.

Europeans left the Old World to establish themselves in the so called
New World, which was certainly not new to the inhabitants that they
displaced.  The Old World's carrying capacity was straining under the
population, and there certainly wasn't much pleasant in the great
cities of London or Paris -- they were fetid caldrons of filth,
disease with a high incendinary index -- which is finally what cleaned
them out.  But as European civilization established itself on the
bones of two continents that had been all but wiped out by small pox
in the Americas and inflicted


** Against

The old argument that we as a civilization should concentrate on
spending resources to solve problems here on earth than to do things
like human exploration and colonization.

  - 
  - [[https://aeon.co/essays/is-a-mission-to-mars-morally-defensible-given-todays-real-needs][Is a mission to Mars morally defensible given today’s real needs?]] | Aeon Essays
  - [[https://qz.com/907211/should-we-live-on-mars-nasa-astronaut-ron-garan-believes-we-should-focus-on-fixing-problems-on-earth-instead-of-martian-colonization/][Should we live on Mars?]] | Quartz
  - [[http://www.foresight.org/nano/Mars.html][Space Development: The Case Against Mars]] | Eric Drexler
  - [[https://e4a-net.org/2017/01/24/why-were-not-going-to-mars-by-timothy-crownshaw/][Why we’re not going to Mars]] | Timothy Crownshaw – Economics for the Anthropocene

** For

#+begin_quote
  Look again at that dot. That's here. That's home. That's us. On
  it everyone you love, everyone you know, everyone you ever heard
  of, every human being who ever was, lived out their lives. The
  aggregate of our joy and suffering, thousands of confident
  religions, ideologies, and economic doctrines, every hunter and
  forager, every hero and coward, every creator and destroyer of
  civilization, every king and peasant, every young couple in love,
  every mother and father, hopeful child, inventor and explorer,
  every teacher of morals, every corrupt politician,
  every "superstar," every "supreme leader," every saint and sinner
  in the history of our species lived there--on a mote of dust
  suspended in a sunbeam.

  The Earth is a very small stage in a vast cosmic arena. Think of
  the rivers of blood spilled by all those generals and emperors so
  that, in glory and triumph, they could become the momentary
  masters of a fraction of a dot. Think of the endless cruelties
  visited by the inhabitants of one corner of this pixel on the
  scarcely distinguishable inhabitants of some other corner, how
  frequent their misunderstandings, how eager they are to kill one
  another, how fervent their hatreds.

  Our posturings, our imagined self-importance, the delusion that
  we have some privileged position in the Universe, are challenged
  by this point of pale light. Our planet is a lonely speck in the
  great enveloping cosmic dark. In our obscurity, in all this
  vastness, there is no hint that help will come from elsewhere to
  save us from ourselves.

  The Earth is the only world known so far to harbor life. There is
  nowhere else, at least in the near future, to which our species
  could migrate. Visit, yes. Settle, not yet. Like it or not, for
  the moment the Earth is where we make our stand.

  It has been said that astronomy is a humbling and
  character-building experience. There is perhaps no better
  demonstration of the folly of human conceits than this distant
  image of our tiny world. To me, it underscores our responsibility
  to deal more kindly with one another, and to preserve and cherish
  the pale blue dot, the only home we've ever known.

  -- Carl Sagan, Pale Blue Dot, 1994
#+end_quote


  - [[https://www.youtube.com/watch?v=ffUnNaQTfZE&t=1030][Supertasks]] | YouTube
  - [[https://www.youtube.com/watch?v=YH3c1QZzRK4][Wanderers]]  | YouTube
  - [[https://en.wikipedia.org/wiki/Pale_Blue_Dot][Pale Blue Dot]]  | Wikipedia
  - [[http://www.planetary.org/explore/space-topics/earth/pale-blue-dot.html][A Pale Blue Dot]] | The Planetary Society
  - [[https://www.youtube.com/watch?v=p86BPM1GV8M][Pale Blue Dot]] | YouTube
  - [[http://www.teslarati.com/yes-deserve-colonize-mars-keep-light-consciousness/][Yes, we deserve to colonize Mars and keep our “light of
    consciousness”]] | Teslarati
  - [[https://launiusr.wordpress.com/2012/02/08/why-explore-space-a-1970-letter-to-a-nun-in-africa/][Why Explore Space? A 1970 Letter to a Nun in Africa]] 

*** Carl Sagan Tribute Series

[[http://www.industrytap.com/wanderers-tormented-everlasting-itch-things-remote/24997][Wanderers Tormented with an Everlasting Itch for Things Remote]] | Industry Tap

- i [[https://www.youtube.com/watch?v=Qfm0GCvsIVA][  A Universe Not Made For Us]] | YouTube
- ii  [[https://www.youtube.com/watch?v=E6kStH-LXgI][Consider Again That Pale Blue Dot]] | YouTube
- iii [[https://www.youtube.com/watch?v=sKtHR1eUubI][Wanderers]] | YouTube




* Core Patterns

 - [[./prolog-cosmos.org][Cosmos]]
 - [[./prolog-process.org][Process]]
 - [[./prolog-holon.org][Holons]]
 - [[./prolog-identity.org][Identity]]
 - [[./prolog-pace.org][Pace Layers]]
 - [[./prolog-scope.org][Scope]]
 - [[./prolog-transactive.org][Transactive Nature]]

* Footnotes

[fn:2] A favela is a portuguese word for an urban area that is
predominately poor and only semi-regulated.  A favela, or barrio is
not slum, though some people confuse favela's for slums.  But they are
deperately crowded.  A favela has electricity, running water and
sewage, and there are many permenant structures, whereas slums
typically do not have any of these things, or if they do they are
disfunctional and not maintained.

See: [[https://en.wikipedia.org/wiki/Favela][Favela]] | Wikipedia

[fn:1] Our ancestors managed to explore and settle the vast majority
of the habitable regions of the planet in ages long past when
Mammoths, Giant Sloths and the Saber Toothed Tiger roamed the
grasslands of North America and Asia.  They interbred with close
relatives, the Neandrthal and Cro Magnon.  Their astonishing
achievement is manifest in the world we live in today, though they
left little evidence of their passing except through the occasianal
burial site or artifact and the mitochondrial DNA, a record passed
from female to female throughout the generations that resides in each
one of us.

It's commonly claimed by so-called aboriginal people's from around the
world that /they/ were first.  The nomads who first explored the
planet predate any human culture by thousands of years.  They are the
ancestors of all humans who came out of Africa and spread across the
world in three successive stages.

