#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Memory
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-memory.org
  :Created: 2017-04-15T19:16@Prek Leap (11.642600N-104.919210W)
  :ID: 5da59e89-1753-4981-a1a1-7fc08bdca9bb
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

We will argue that what set humans apart from everything
else was the development of a large neo-cortex which can be
seen as a general purpose computer that wrapped around and
extended the older layers of brain at the center.

The neo-cortex was able to reprogram itself, it wasn't
hardwired and programed by evolutionary processes.

The neo-cortex is connected to the world through senses, and
it is able act on the world through muscle.  Tools likely
came first and extended man's muscles.  Spoken language
became the first means of extending the neo-cortex by
linking to other neo-cortexes in a group, which resulted in
a revolution in transactive memory.

Written symbol systems extended memory through time and
space, and moveable type and the printing press made it a
reliable form for duplication for transmission.

Recorded media -- that could sample, record, store and play
back what was seen and heard made possible to create
reliable records of what our senses tell our brain, creating
an entirely new kind of memory from human biological
memories.

The forerunner to this was of course painting and sculpture,
but are completely different in many respects because fine
art never records a moment, but consolidates any number of
moments into a single image.  This is something that
recorded memory does not do.

Computers are cognitive extensions to the neo-cortex --
programs are cognitive processes.

Tools, plus a power source became machines, machines plus a
cognitive or memory device become robots.


Memory takes many forms, but we will break it down into:

  - Genetic
  - Internal (Human)
    - short, medium, long term
    - muscle memory
  - External
    - Human (group)
    - Animal (domesticated animals)
    - Sound & Sight
    - Recordings & Symbols
    - Analog Media (clay, stone, paper)
    - Digital (binary electronic)

Time

  - immediate
  - cyclical (day/night, seasonal, yearly etc)
  - generational
  - institutional (individuals can't remember long term,
    institutions do that for us)

* Transactive Memory

All pack animals have varying amounts of transactive
memory.  But there is not much in the way of specialization
beyond an alpha leader, and biological specialization

Hunter & Gather are specializations that grew from
biological specializations.  The domestication of the dog
was a transactive relationship -- dogs weren't kept for
meet, they helped with hunts, and their senses extended
man's allowing man to develop parts of the brain for tasks
that were now dog's job.

agriculture and domestication of key animals made possible
an explosion of specialization which made civilization possible.


* Cognitive Future Bias

- [[http://www.slate.com/articles/technology/future_tense/2017/04/why_people_are_so_bad_at_thinking_about_the_future.html][Why people are so bad at thinking about the future.]] | Jan
   McGonigal, Slate

In one sense, your brain is right, the future you is not
you, it will be a very different person from you today, all
but a stranger who will have share some fuzzy and often just
plain wrong memories with you.


* Seven generation sustainability


 - [[https://en.wikipedia.org/wiki/Seven_generation_sustainability][Seven generation sustainability]] - Wikipedia


#+begin_quote
Seven generation stewardship is a concept that urges the
current generation of humans to live and work for the
benefit of the seventh generation into the future.[citation
needed] It originated[citation needed] with the Iroquois -
Great Law of the Iroquois - which holds appropriate to think
seven generations ahead (about 140 years into the future)
and decide whether the decisions they make today would
benefit their children seven generations into the future. It
is frequently associated with the modern, popular concept of
environmental stewardship or 'sustainability' but it is much
broader in context (see the quotation below relative to "in
ALL your deliberations ...".

-- [[https://en.wikipedia.org/wiki/Seven_generation_sustainability][Seven generation sustainability]] - Wikipedia
#+end_quote
