#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Creating a Movement
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-movement.org
  :Created: 2017-03-19T11:03@Prek Leap (11.642600N-104.919210W)
  :ID: a697ee48-a891-4ad4-9350-b2f07e054b3f
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

  - rules for radicals
  - stupid tedtalk video
  - methodist movement
  - what we can learn from religion

* Overton Window

  - [[https://en.wikipedia.org/wiki/Overton_window][Overton window]] | Wikipedia

#+begin_quote
"Many who before regarded legislation on the subject as chimerical,
will now fancy that it is only dangerous, or perhaps not more than
difficult. And so in time it will come to be looked on as among the
things possible, then among the things probable;–and so at last it
will be ranged in the list of those few measures which the country
requires as being absolutely needed. That is the way in which public
opinion is made."

"It is no loss of time," said Phineas, "to have taken the first great
step in making it."

"The first great step was taken long ago," said Mr. Monk,–"taken by
men who were looked upon as revolutionary demagogues, almost as
traitors, because they took it. But it is a great thing to take any
step that leads us onwards."

-- [[https://en.wikipedia.org/wiki/Phineas_Finn][Phineas Finn]] | [[https://en.wikipedia.org/wiki/Anthony_Trollope][Anthony Trollope]]
#+end_quote
