#   -*- mode: org; fill-column: 60 -*-

#+TITLE: The Great Plateau
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/prolog-great-plateau.org
:Created:   2017-09-20T19:43@Prek Leap (11.642600N-104.919210W)
:ID:        8118c15d-8977-4919-81dc-ec99879165a8
:VER:       559183480.839484216
:GEO:       48P-491193-1287029-15
:BXID:      proj:ROI4-2277
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

It's interesting that in all of the possible scenarios proposed to
answer Fermi's Paradox, the one that you hear little or nothnig about
is the idea that man doesn't destroy herself, but rather hits a
technological plateau where any future advances become so difficult
that they become a case of diminishing returns.

Man has hit many plateaus, some of which lasted milennia or at least
centuries.  In historical times these plateaus have often been called
dark ages, at least over the last two hundred years.  The average
person living in the middle of most of these dark ages wouldn't have
considered their time dark, just that not a lot changed.

The periods of plateau correspondended with no or low population
growth and though there were certainly no lack of wars, the wars just
sort of churned things rather than resulted in any great change.

The idea of a plateau runs counter to the whole modern notion of
progres.  A plateau is not a good thing.  It represents stagnation, of
staleness that if nothing else is just not very interesting.  Not a
lot of history emerges from dark ages because there wasn't a lot to
write about.  You had king following king following king, with the
wars that were fought between them, and that's about it.

But a plateau is not evil, it is neutral, neither progressing forward
or in decline.  For a species, a log sustained plateau is a the sign
of a highly successful species, who is well adapted to its ecological
niche and is not so specialized that it an ride out flucuations in the
the climate over long periods of time.

During plateaus, time is not thought of as linear but circular,
following the sun and the moon and the seasons.  What specific year it
was relative to centuries and milennia were not important.  Time was
relative to the solar cycles and to yourself and those around you in
your family, band or village.

The shift is actually far more recent than is remembered. In fact it
has happened in my life time.  At the beginning of the second half of
the 20th century, it was commonly thought that science had nearly
figured  everything out, that all the great discoveries were behind us
and that all that was left was to refine the formula's fill in the odd
blank spot in our theories and have done with it.  

I remember reading more than one article like this when I was in
school in the late 1970's and found it disheartening.  Even in high
school it didn't sound quite right.  The Standard Model was brilliant,
but it was far too messy, and couldn't reconcile the queerness of how
things worked at quantum scales, the hundrum world we directly
experience with our senses and the fantastic realms of the
relativistic.  They were simply too different.

I used to read a weekly science newsletter that was no more than 3-4
pages long, sitting in a battered chair in the magazine section of the
tiny high school library where I took refuge to read and study outside
of the school's pedestrian curriculum.  The science was far beyond my
level, but I tried my best to understand the work described.  I'd
given up asking any of my teachers for help in understanding either.
It seemed as if it was as far over their heads as mine.

But I knew, there /had/ to be more.  The universe /couldn't/ be as
clunky as science could describe it at that time.

     *NOW tie the narrative back to the end science*

Only a fool would dare say such a thing today.

History is littered with such prognostications.  That man could not
survive moving faster than a few hundreds of kilometers per hour
without risking certain death.  Then it was the fear that man could
not travel faster than the speed of sound.  Or could never survive in
the extremes of leaving the earth, or survive in free fall etc.  Until
recently this was the norm in science, not the exception.

Einstein was scolded in university for conjectures about atoms and
molecules which were not, had not yet reached a scientific consensus
of their existence.

We still hadn't wholly surrendered to the now holy doctrine of the
inevitibility of progress in the same way we have today. We are all
like Alice's Red Queen, imagining at least XX impossible things before
breakfast.

Time is a straight arrow heading in one direction.  And the unspoken
and unchallenged belief is that even if there are declines or even
plateaus, they are tempory aberrations that are discarded from the
plot, chaff blown away from the falling wheat.  The overall trend is
forward and forever up.  We call this progres, and it is the one god
that all modern belief systems sacrifice to, though they aren't aware
they are doing so.  Progress is the one unchallenged asumption that
modern man makes that is thought to be so obvious that it is like
challenging the rising of the sun or that gravity might not be
absolute.  In fact, we would happily entertain, or at least suspend
belief in even the physical laws of the universe before we would
challenge the absolute truth of progress.

In terms of mankind's short existence in this planet, the case for
endless progress seems undeniable.  But it ignores the fact that we
live in a physical universe based on very inflexible laws of matter,
energy, space and time.  We live in tenuous razor thin biosphere that
envelops the planet like the skin of an apple.

The biosphere has largely been cumulatively shaped by countless
organisms, over billions of years, that is responsible for the
atmosphere we breath, and the complexity of life that even makes our
species possible.

We are reaching a threshold where man will no longer be constrained by
he accidental evolutionary whims the govern our genes, which until now
are what really have called the shots on this planet.  We can now
manipulate matter at both microscopic, and even atomic scales as well
as at planetary scales.  We are on the cusp of becoming gods in the
aggregate even if as individuals we are still little more than clever
hairless apes who have moved from our ecological niche on the savannah
in an evolutionary blink of the eye, to become the planet's apex
predator.  This has happened so fast that we still haven't learned how
to think and behave like an apex predator.  And in turn, the flora and
fuana around us haven't had time to catch up and develop means of
keeping us in check.

The one thing that should have kept us in check was population growth,
which should have killed us off many times in the past.  But we are
tool builders, masters of adaptation, and adapting the world around us
to allow us to survive and even thrive in places we really have no
right being.

But how long can this continue?  There are very real physical limits
to the universe, how much energy we can generate and consume (at least
in our solar system), how fast our computers can flip bits, how much
information can be stored, how fast we can travel etc.  



It is true that we have only exploited a tiny fraction of what can be
done within those limits.  But here is the thing.  We don't know how
far we can continue to improve technology.  We will eventually hit a
wall where advances will become fewer and farther apart.  Our
technological progress has been advancing exponentially.  Human's
aren't able to grasp exponential anything.  The savannah had no need
for such concepts.  We simply can't comprehend the situation we are in
today.  And still the question remains, how far can we push?  How many
doublings do we have ahead of us before it all grinds to a snails pace
and we hit our Great Plateau.

Perhaps this is why we haven't seen evidence of Dyson Spheres in our
Galaxy or seen evidence in other Galaxies under the control of
fantastically advanced civilizations whose signatures can be seen even
from where we are here on earth.
 
So again, how many doublings do we still have ahead of us, and where
will it leave us when we do plateau?  It's not a matter of if, but
when.  And we shouldn't be so arrogant to think that it will be our
handful of generations that will see the absolute last plateau.  Our
plateau may last millenia or even longer before the next breakthrough
that sends us hurtling towards another singularity.  Where it ends is
anybody's guess.

And that's the thing.  The singularity is not ahead of us, we are
smack dab in the middle of the singularity and we have no idea what
will happen next.  That's Vinge's original definition of a
singularity, that things are changing so fast that it's impossible to
predict what will happen next.  It's exhilarating and terrifying at
the same time, a roller coaster in hurtling in the darkness, which we
haven't noticed has long been freed of any guidance of the tracks.
