#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Muscle
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-muscle.org
  :Created: 2017-04-15T19:18@Prek Leap (11.642600N-104.919210W)
  :ID: 42c19dca-114c-46bd-a854-8bbc5936eacd
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction



#+begin_quote
A person at rest is using energy at the rate of about 80
watts, similar to the energy requirement of an incandescent
light bulb. A person doing heavy work is likely to generate
energy at 8–10 times this rate. The watt is a basic unit of
power, which is the rate of use, or generation, of
energy. The best-known unit for measuring energy is the
joule: 1 watt is 1 joule per second.20 The watt is named
after James Watt, the inventor of the most useful form of
steam engine. In 2010, the energy required for all human
activities, including that generated by people but excluding
the output of animals, used in jobs in agriculture or for
trans- port, was 536 exajoules or 536 billion billion (1018)
joules. 

--  [[bib:marsh:2012new][The New Industrial Revolution]] pg 31 | Peter Marsh (2012)
#+end_quote

