#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Muscle
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/prolog-muscle.org
:Created:   2017-04-15T19:18@Prek Leap (11.642600N-104.919210W)
:ID:        42c19dca-114c-46bd-a854-8bbc5936eacd
:VER:       551810031.630315278
:GEO:       48P-491193-1287029-15
:BXID:      proj:WPG1-8106
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

Everything started with human muscle:

#+begin_quote
A person at rest is using energy at the rate of about 80
watts, similar to the energy requirement of an incandescent
light bulb. A person doing heavy work is likely to generate
energy at 8–10 times this rate. The watt is a basic unit of
power, which is the rate of use, or generation, of
energy. The best-known unit for measuring energy is the
joule: 1 watt is 1 joule per second.20 The watt is named
after James Watt, the inventor of the most useful form of
steam engine. In 2010, the energy required for all human
activities, including that generated by people but excluding
the output of animals, used in jobs in agriculture or for
transport, was 536 exajoules or 536 billion billion (1018)
joules. 

--  [[bib:marsh:2012new][The New Industrial Revolution]] pg 31 | Peter Marsh (2012)
#+end_quote

First tools were invented that extended our limbs, and
allowed us to do things like move and carry water, cut wood,
and make weapons that could kill game that we could not kill
unaided.

Tools made it possible to increase the amount of force that
we could apply.

Next, we harnessed animals -- first was the dog, who helped
us hunt and through their more powerful senses of hearing
and smell, to warn us of approaching danger.

Next we harnessed animals to work.  This did not happen
everywhere because there weren't many species that could be
domesticated for work -- so we got the horse, and cow and
not much else.  The llama wasn't good for much more than
transportation.

   Look up list of species Jared Diamond gives in Germs,
   Guns and Steel.

#+begin_quote
The power available from a horse is about 500 watts,
equivalent to six people of average physique working
reasonably hard.

-- [[bib:marsh:2012new][The New Industrial Revolution]] pg 31 | Peter Marsh (2012)
#+end_quote

#+begin_quote
Another source of energy was to harness the power from
natural sources such as fast-moving rivers or strong
winds. Watermills have existed since Roman times. In 200 ce,
a Gallo-Roman settlement near Arles, in what is now France,
had 16 water wheels.21 They drove a series of corn mills,
grinding 28 tonnes of wheat a day. According to the Domesday
Book, eleventh-century Britain had 5,624 watermills.22 Over
the next few hundred years, windmills became wide- spread in
Europe and elsewhere. Windmills were more adaptable than
watermills. Many designs allowed them to swivel to align
with whichever direction the wind was blowing, increasing
their usefulness.23 Watermills and windmills were used for
jobs such as grinding corn or operating rudi- mentary
machinery to blow the air into blast furnaces. But the
amount of energy available from water- or wind-powered
machinery was limited. A medieval watermill could supply no
more than 1.5 kilowatts (1,500 watts).  Even the biggest
medieval windmill generated only about 7.5 kilowatts. A
modern truck generates energy at a rate 35 times higher.

-- [[bib:marsh:2012new][The New Industrial Revolution]] pg 31 | Peter Marsh (2012)
#+end_quote



When mechanical power sources were invented, which came down
to wind and water, we put them together with tools and got
our first machines.  A windmill turning a millstone, or
hammer are both primitive types of machines.

  - then came Steam engines

#+begin_quote
In 1698, Thomas Savery of Totnes, in Devon, south-west
England, published a patent describing how to raise a fluid
such as water ‘by the impellent force of fire’. Savery’s
device was the first steam engine, based on heating a supply
of water in a boiler using coal. The steam passes into a
series of cylinders. As the steam condenses inside each one
to re-form water, it contracts, forming a partial
vacuum. Assuming the cylinders are linked by pipes to the
water that needs to be lifted, the atmospheric pressure
acting on this water forces it into the unoccupied
space. Savery’s design provided one of the first workable
ways to transfer energy from a fossil fuel into movement
that could be used for a range of jobs.

In 1708, Thomas Newcomen, another Devon engineer, produced
an improved engine that incorporated rods and other
mechanisms that could drive machinery. In 1769, the Scottish
inventor James Watt unveiled a still better machine that
used energy more efficiently (less was wasted) than
Newcomen’s engines. Soon afterwards, the first large-scale
factories started to appear in Britain. .... Watt’s engines
became the prime power source for the factories that
featured in the first industrial revolution. By 1870, steam
engines used in Britain and based on the inventor’s design
produced an output of 3 gigawatts (3 billion watts) –
equivalent to the work of 6 million horses. In 1890, steam
engines produced almost 80 per cent of the energy
requirements for US factories, superseding waterpower which
up to the 1850s had remained the main energy source.24


-- [[bib:marsh:2012new][The New Industrial Revolution]] pg 32 | Peter Marsh (2012)
#+end_quote

#+begin_comment
wheels led to bearings which are one of the foundational
parts of industrial civilization -- bearings are in vast
array of manmade things.
#+end_comment

  - then came Internal Combustion
  - then came electricity

Electronics allowed us to build in some amount of
self-guidance by creating hard-coded programs that
controlled machines and greatly reduced the need for human
control.

What is happening now is that general purpose programable
computers are being used to control machines.  This is all
that a robot is.  A program controlling a machine.







