#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Minimum & Maximum Viability
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/prolog-viability.org
  :Created: 2017-04-16T19:21@Prek Leap (11.642600N-104.919210W)
  :ID: 44a4538c-72b0-4ff3-a919-c75c1e67f08b
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

Once we have accepted the wisdom of the LOCKSS model and that this
provides Mankind with it's best chance of maximizing it's long term
survival and sustained level of properity we face the rather daunting
task of determining what is the minimum size in terms of population,
technology, tools and skills required that constitute a sustainable
technological civilization.  That would give us a baseline for how
many instances of civilization that we can theoretically maintain
any given population.

As anyone who is familiar with maintaining computer backups, it is not
as simple a creating a bunch of copies.  There are many different
statistical models that can be used to determine how many copies can
be maintained in such a way that X number of copies can be destroyed
and still reconstitute anything that has been lost.  This means that
we don't have to use the same brute force duplication that DNA
employess to achieve the same results.  But before we can get into any
of that we need to determine a number of minimal viability parameters
that taken together constitute a sustainable civilization.

In one respect, this could be the single most important reason to go
to Mars other than Mars as a backup of Earth.  It may be impossible to
know for certain what real minimum viability is unless we can build
and demonstrate it in the real world, or at least on another, real
world like Mars.

Civilization is such a large, dynamic, complex system that it is like
the weather, the number of variables and interactions is beyond
meaningful prediction beyond very short term, and crude projects that
even then are not always accurate.

* Minimum Viable Thresholds


- Minimum Viable Population
- Minimum Viable Biodiversity
  - wild
  - cultivated
- Minimum Viable Specialties
- Minimum Viable Toolset
- Minimum Viable Materials
  list of raw materials
- Minimum Viable Elements
  list of metals, chemicals, gases etc
- Minimum Viable Compounds
  chemical compounds

* Minimum Viable Complexity

Minimum Viable Complexity it made up of:

  - Min Viable Population (MVP)
  - Min Viable Tools (MVT)
  - Min Viable Specialties (MVS)
  - Min Viable Processes (MVP)

Start with MVP, then divide that number into backup or jumpstart
communities of 1,500 to 2,500 individuals.  At the core of those
communities will be a cloistered community at or smaller than the
Dunbar number, whose sole job is the collection, preservation, and
distribution of information, and to keep all MVS in living memory
within the community.

When at minimum, one of these communities has been established on an
planet or moon other than earth, man will have become a multi-planet
species.

These communities will also become the center of new very long term
institutions that are independent of religious or secular
organizations.  The group that controls the territory surrounding
each enclave will maintain a treaty that they will not interfere or
participate in any way, but will act as a long term repository and
information broker for that territory if they desire it.  Neutrality,
and silence will be maintained -- and the enclave will remain
isolated. 

We will establish MVC for three different levels of complexity:

  - 18th century :: peak of agracultural, mechanisms, advanced 
                    tools -- it would be cool to include bio-
                    engineered things like page trees, biolumin
                    lighting, and synthetic photosynthesis for
                    very small scale electricty,
  - 19th century :: peak of mechanical + electricity, 
                    internal combustion, thorium & hydrogen
                    power sources.
  - 21st century :: computer controlled matter fabrication
                    and compiling, robotics, DNA sequencing 
                    and manipulation, advanced networks, 
                    storage and computation, thorium & 
                    hydrogen power sources.

This will have to be done for several different climates and parts of
the world:

  - tropical
  - desert
  - temperate
  - arctic

These levels will not meant to be historically accurate, that's not
the intention.  But each of these eras represent a base-line for
complexity at different times in the past.  The goal is to achieve the
best possible quality of life for a minimum and maximum population
size at a given level of complexity.

* Minimum Viable Community

What is the minimal viable size of a community to maintain our present
civilization? 

** Minimum Genetic Pool
*** Minnumber of skill sets
*** Minumum-Maximum Environmental Range
**** Min-Max temperature range
**** Min-Max potable water
**** Min-Max sunlight
**** Min arable land
*** Minimum Biodiversity
**** Domestic
***** Min number of plants
***** Min number species
**** Wild
***** plants and animals

In the case of animals and plants in the wild, we must look at this in
terms of extinction events.  What will crash food chains and
eco-systems.

Eco-systems are a crucial part of maintaining weather cycles -- the
ecology of the planet drives a lot of weather -- 



* Carrying Capacity 

  - [[https://en.wikipedia.org/wiki/Carrying_capacity][Carrying capacity]] | Wikipedia

A more common term for the maximum viability of an ecosystem is of
course its /carrying capacity/.

This is certainly not limited to humans -- when locust swarm they
quickly exhaust the carrying capacity of a region which results in a
collapse and die-off of the population.

Human civilization is an almost cyclical progression of successful
populations exceeding the carrying capacity of their ecosystems, at
which time there is collapse and a die-off.

The carrying capacity is not a hard number, it depends on a number of
different parameters that can be leveraged to increase or decrease
that capacity.  
