#   -*- mode: org; fill-column: 60 -*-

#+TITLE: The Great Plateau
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/prolog-great-plateau.org
:Created:   2017-09-20T19:43@Prek Leap (11.642600N-104.919210W)
:ID:        8118c15d-8977-4919-81dc-ec99879165a8
:VER:       559183480.839484216
:GEO:       48P-491193-1287029-15
:BXID:      proj:ROI4-2277
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

It's interesting that in all of the possible scenarios proposed to
answer Fermi's Paradox, the one that you hear little or nothnig about
is the idea that man doesn't destroy herself, but rather hits a
technological plateau where any future advances become so difficult
that they become a case of diminishing returns.

Man has hit many plateaus, some of which lasted milennia or at least
centuries.  In historical times these plateaus have often been called
dark ages, at least over the last two hundred years.  The average
person living in the middle of most of these dark ages wouldn't have
considered their time dark, just that not a lot changed.

The periods of plateau correspondended with no or low population
growth and though there were certainly no lack of wars, the wars just
sort of churned things rather than resulted in any great change.

The idea of a plateau runs counter to the whole modern notion of
progres.  A plateau is not a good thing.  It represents stagnation, of
staleness that if nothing else is just not very interesting.  Not a
lot of history emerges from dark ages because there wasn't a lot to
write about.  You had king following king following king, with the
wars that were fought between them, and that's about it.

But a plateau is not evil, it is neutral, neither progressing forward
or in decline.  For a species, a log sustained plateau is a the sign
of a highly successful species, who is well adapted to its ecological
niche and is not so specialized that it an ride out flucuations in the
the climate over long periods of time.

During plateaus, time is not thought of as linear but circular,
following the sun and the moon and the seasons.  What specific year it
was relative to centuries and milennia were not important.  Time was
relative to the solar cycles and to yourself and those around you in
your family, band or village.

But modern man wants none of that.  Time is a straight arrow heading
in one direction.  And the unspoken and unchallenged belief is that
even if there are declines or even plateaus, they are tempory
aberrations that are discarded from the plot.  The overall trend is
forward and forever up.  We call this progres, and it is the one god
that all modern belief systems sacrifice to, though they aren't aware
they are doing so.  Progress is the one unchallenged asumption that
modern man makes that is thought to be so obvious that it is like
challenging the rising of the sun or that gravity might not be an
absolute law.

In terms of mankind's short existence in this planet, the case for
endless progress seems undeniable.  But it ignores the fact that we
live in a physical universe based on very inflexible laws of matter,
energy, space and time.  We live in tenuous razor thin biosphere that
envelops the planet like the skin of an apple.

The biosphere has largely been cumulatively shaped by countless
organisms, over billions of years, that is responsible for the
atmosphere we breath, and the complexity of life that even makes our
species possible.

We are reaching a threshold where man will no longer be constrained by
he accidental evolutionary whims the govern our genes, which until now
are what really have called the shots on this planet.  We can now
manipulate matter at both microscopic, and even atomic scales as well
as at planetary scales.  We are on the cusp of becoming gods in the
aggregate even if as individuals we are still little more than clever
hairless apes who have moved from our ecological niche on the savannah
in an evolutionary blink of the eye, to become the planet's apex
predator.  This has happened so fast that we still haven't learned how
to think and behave like an apex predator.  And in turn, the flora and
fuana around us haven't had time to catch up and develop means of
keeping us in check.

The one thing that should have kept us in check was population growth,
which should have killed us off many times in the past.  But we are
tool builders, masters of adaptation, and adapting the world around us
to allow us to survive and even thrive in places we really have no
right being.

But how long can this continue?  There are very real physical limits
to the universe, how much energy we can generate and consume (at least
in our solar system), how fast our computers can flip bits, how much
information can be stored, how fast we can travel etc.  



It is true that we have only exploited a tiny fraction of what can be
done within those limits.  But here is the thing.  We don't know how
far we can continue to improve technology.  We will eventually hit a
wall where advances will become fewer and farther apart.  Our
technological progress has been advancing exponentially.  Human's
aren't able to grasp exponential anything.  The savannah had no need
for such concepts.  We simply can't comprehend the situation we are in
today.  And still the question remains, how far can we push?  How many
doublings do we have ahead of us before it all grinds to a snails pace
and we hit our Great Plateau.

Perhaps this is why we haven't seen evidence of Dyson Spheres in our
Galaxy or seen evidence in other Galaxies under the control of
fantastically advanced civilizations whose signatures can be seen even
from where we are here on earth.
 
So again, how many doublings do we still have ahead of us, and where
will it leave us when we do plateau?  It's not a matter of if, but
when.  And we shouldn't be so arrogant to think that it will be our
handful of generations that will see the absolute last plateau.  Our
plateau may last millenia or even longer before the next breakthrough
that sends us hurtling towards another singularity.  Where it ends is
anybody's guess.

And that's the thing.  The singularity is not ahead of us, we are
smack dab in the middle of the singularity and we have no idea what
will happen next.  That's Vinge's original definition of a
singularity, that things are changing so fast that it's impossible to
predict what will happen next.  It's exhilarating and terrifying at
the same time, a roller coaster in hurtling in the darkness, which we
haven't noticed has long been freed of any guidance of the tracks.
