#   -*- mode: org; fill-column: 60 -*-
#+STARTUP: showall

* Chenla Prolegomenon
  :PROPERTIES:
  :CUSTOM_ID: 
  :Name:      /home/deerpig/proj/chenla/prolog/README.org
  :Created:   2017-06-22T11:37@Prek Leap (11.642600N-104.919210W)
  :ID:        2c816d16-ca6b-4f9e-a5f3-e5d47ac5d5fc
  :VER:       551378298.454409166
  :GEO:       48P-491193-1287029-15
  :BXID:      proj:RCL1-6613
  :Category:  primer
  :Entity:    readme
  :Status:    wip 
  :Licence:   MIT/CC BY-SA 4.0
  :END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]]
[[https://img.shields.io/badge/category-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/entity-readme-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

The larger purpose of the prolegomenon is to provide an introduction
to the concepts and contextual and social assumptions that the
/Primer/ is based on.  In that sense this will be the primer for the
/Primer/.

Dictionaries define a /prolegomenon/ as a discursive introduction; a
map of a territory.  But sometimes the territory is so expansive that
the map that models it is great enough to warrant a map of it's own...
Ranganathan's Prolegomenon was such an introduction.  Wordsworth's
/Prelude/ ate up so much time and space that the /Recluse/ was never
completed....

I fear that this will be the fate of my humble literate computational
prolegomena as well.

The idea is that these texts can be used to construct a number of
narratives that can be published in traditional formats to act as a
bridge, or at least a beartrap that drops you down the rabbit hole.

Beware the pointy bits at the bottom when you land...

