#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Prolegomena References
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/prolog/ref-prolog.org
:Created:   2017-04-29T17:50@Prek Leap (11.642600N-104.919210W)
:ID:        22d37595-e4ec-4b44-87c2-73e96ed916eb
:VER:       551831796.260207619
:GEO:       48P-491193-1287029-15
:BXID:      proj:CNG1-6554
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]


* Introduction

  :TREE:
  :BT: (prop value)
       (owner deerpig)

   [  ][  ]

   value      -- for the relationship - implies self as prov
   prop value -- key value pair - implies self as prov
   triple     -- triple - implies self as prov
   quad       -- external prov

  :END:



* Scope Note                                       :SN:

The idea here is that every reference is a burr

For now we will include the bibtex entry for each reference
in a src block that is tangled to create latex references.
Later we will generate the bibtex from the metadata in the
Burr.

But these burrs will go beyond being only bibliographic
references, they can be definitions, authority records, and
blob records.

In fact, eventually, it should be relatively rare to have to
create these on your own.  There should be public catalogs
online that you can download locally or link to over the
Internet.

This is the thin edge of the web where BMF begins in ernest.

It doesn't matter where we begin -- here is as good a place
as any, but we will have to define everything in the
process, which will build out chenla/core  that will define 
all of the BMF burrs and eventually move most of the entries
here into larger collections.  The mechanism for this is yet
to be determined.  But hey, this is a bottom up process.
I've spent enough years thinking about it top down, so let's
see if we can no implement it bottom up.


