#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Prolegomena References
#+AUTHOR: Brad Collins
#+EMAIL: brad@chenla.la
#+PROPERTY: header-args    :results drawer  :tangle ref-prolog.el

#+STARTUP: showall
#+PROPERTY: filename
#+TOC: headlines 4
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/ref-prolog.org
  :Created: 2017-04-29T17:50@Prek Leap (11.642600N-104.919210W)
  :ID: 22d37595-e4ec-4b44-87c2-73e96ed916eb
  :VER: 546735262.598557129
  :BXID: GRO44-6794
  :TSPACE: prolog/works/org.chenla
  :CUSTOM_ID: Prolegomena_References_()
  :URL:
  :END:

  :TREE:
  :BT: 


  :END:



* Scope Note                                       :SN:

The idea here is that every reference is a burr

For now we will include the bibtex entry for each reference
in a src block that is tangled to create latex references.
Later we will generate the bibtex from the metadata in the
Burr.

But these burrs will go beyond being only bibliographic
references, they can be definitions, authority records, and
blob records.

In fact, eventually, it should be relatively rare to have to
create these on your own.  There should be public catalogs
online that you can download locally or link to over the
Internet.

This is the thin edge of the web where BMF begins in ernest.

** 

