#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Fnord
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/prolog/structure-fnord.org
  :Created: 2017-04-21T12:07@Prek Leap (11.642600N-104.919210W)
  :ID: 3f9a27e8-f283-420d-a61b-9eb13a3f755a
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

#+begin_comment
How does the fnord as outlined below compare to the /meme/
-- memes are not true or false in themselves but they have a
life of their own.

It would be good to be able to reconcile the two...
#+end_comment


For a simple model, this works quite well, but only when you
stay at the same scale.

Our example above: /Chasui's age is 6/ doesn't help us
define what a Chasui is, or what is a year.  So let's turn
our triple into a property list, that provides keys for each
value in the triple:

#+begin_src emacs-lisp
  (("name" . "Chasui") ("relationship" . "age") ("years" . 6))
#+end_src

So now we know that Chasui is a name, that age is a
relationship and the value 6 is in years.  This is better,
and this kind of a property list can be used to create some
very powerful data structures.  Graph databases are built
using property triples.

But the keys are just strings -- they may or may not meaning
anything.  What is a "name", "relationship", "age" or
"year"?  In traditional key-value pairs, these keys are
indeed no more than strings.  They are not required to be
defined in a schema beyond the data structure that they are
part of.

This might not sound important at first, after all we all
know what a "name" is.  Humans who are English speakers who
live at this time in history will know what a name is, but
will software that reads the statement see it as anything
more than a string?  Or for that matter, what if it is read
in the distant future by people who have never heard about
English?

The problem is that there is no way of knowing if this
statement is true or not.  So we don't know if this
statement is fact, fancy, fiction or a falsehood.  This is
because the statement in itself is not enough to assertain
if the statement is a fact.

So let's first tackle the problem of definitions. Instead of
letting something like "name" hanging in the air as if it
means something, we can require that all keys be defined.  A
definition is made up of a group of assertions that taken
together explain what something is. A definition can be
thought of as placing limitations on what something is.  And
when we define something, it needs to be both human
understandable as well as machine understandable.  We can do
this by applying tests.  A test will take a pattern and
compare the pattern to what you are trying to identify, if
the pattern matches the thing your looking at, then that
thing belongs to the set of things that has a label (which
could be a word (string) or other id) that represents that
set.

So any assertion will be made up of many other assertions
that define and create the context for any given statement.
This creates a highly complex mesh of interconnected and
interdependent statements.  Change any one of these
statements may result in changing any number of other
statements -- changing anything in the system requires those
changes to propagate out throughout the system so that all
other statements that are effected can be corrected.

Static data structures will not be able to accomplish this
-- these have to be active dynamic processes.

Even this is not enough because the truth of any statement
depends on the surrounding context when the statement is
observed (read).  When you hear a statement like Chasui is 6
years old, it might be true at the time that the statement
is observed.  However, statements are recorded, so that if
Chasui was born in the year 2000, she would be six years old
if the statement was observed in 2006.  But if the statement
was read in 2020, it would no longer true unless the
statement was ammended to say that Chasui was 6 years old
in 2006.  If the statement said that Chasui was 6 years old
in 2001 that would be false because there is no scenario
where she could have been born in 2000 and then be 6 years
old in 2001.  In otherwords, there is no possible
causal-chain linking the statement and the observation.
However, the statement that Chasui was 6 years old in 2006
will remain true no matter how far into the future that the
statement is observed.

----

Establishing facts is related to naming things

  - [[http://reason.com/archives/2012/12/24/half-the-facts-you-know-are-probably-wro][Half the Facts You Know Are Probably Wrong]] | Reason.com
  - [[bib:arbesman:2012half-life][The Half-Life of Facts]] | Samuel Arbesman, 2012

#+begin_quote
Ordering our surroundings is the rule of how we as humans
operate. In childhood we give names to our toys, and in
adulthood we give names to our species, chemical elements,
asteroids, and cities. By naming, or, more broadly, by
categorizing, we are creating an order to an otherwise
chaotic and frightening world.  

And when we learn facts, we are doing the same
thing. Facts—whether about our surroundings, the current
state of knowledge, or even ourselves—provide us with a
sense of control and a sense of comfort. When we see
something out of the corners of our eyes around dusk, we
needn’t view it as a creepy bird of the night: We call that
a bat, which is a winged nocturnal mammal that “sees”
through the use of echolocation and is probably afraid of
the bipedal mammals around it. Only half as scary, right?

-- The Half-Life of Facts
#+end_quote


#+begin_quote
And there’s one simple way to organize facts, even before we
understand all the math and science behind how knowledge
changes. We can organize what we know by the rate at which
it changes.

Imagine we have all the facts in the world—those pieces of
knowledge that contain all that we know—lined up according
to how often they change. On the far left we have the
fast-changing facts, the ones that are constantly in
flux. These are things such as what the weather will be
tomorrow or what the stock market close was yesterday. And
on the far right we have the very slow-changing facts, the
ones that for all practical purposes are constant. These are
facts such as the number of continents on the planet or the
number of fingers on a human hand.

In between we have the facts that change, but not too
quickly—and are therefore that much more maddening to deal
with. These facts might change over the course of years or
decades or a single lifetime. How many billions of people
are on the planet is one of these. I learned five billion in
school, and we just recently crossed seven billion, as
of 2012. My grandfather, who was born in 1917, learned there
were fewer than two billion. The number of planets outside
the solar system that have been discovered, or, for that
matter, the number of planets in our own solar system, is
also in this category. What we know about dinosaurs is in
this group of facts, as is the average speed of a
computer. The vast majority of what we know seems to fall
into this category, which I call mesofacts—facts that change
at the meso-, or middle, timescale.

-- The Half-Life of Facts
#+end_quote






We need a concept that we can use to include all of the
different possibile combinations that can apply to a given
assertion.  To my knowledge there isn't a word for this, so
we will call it a /fnord/.  You may or may not know what a
fnord is, and in fact you may have heard the word and been
told what it means and still have no real idea what it
means.  And so fnord is a good choice.

Our fnord is both true and false, ugly and beautiful, cruel
and kind, shallow and deep, brilliant and stupid, and every
shade of anything inbetween. A fnord is Borge's [[https://en.wikipedia.org/wiki/The_Library_of_Babel][Library of
Babel]] that contains every possible book.

#+begin_quote
Borges' narrator describes how his universe consists of an
enormous expanse of adjacent hexagonal rooms, each of which
contains the bare necessities for human survival—and four
walls of bookshelves. Though the order and content of the
books is random and apparently completely meaningless, the
inhabitants believe that the books contain every possible
ordering of just 25 basic characters (22 letters, the
period, the comma, and the space). Though the vast majority
of the books in this universe are pure gibberish, the
library also must contain, somewhere, every coherent book
ever written, or that might ever be written, and every
possible permutation or slightly erroneous version of every
one of those books. The narrator notes that the library must
contain all useful information, including predictions of the
future, biographies of any person, and translations of every
book in all languages. Conversely, for many of the texts
some language could be devised that would make it readable
with any of a vast number of different contents.

Despite—indeed, because of—this glut of information, all
books are totally useless to the reader, leaving the
librarians in a state of suicidal despair.

-- [[https://en.wikipedia.org/wiki/The_Library_of_Babel][The Library of Babel]] | Wikipedia
#+end_quote

The library is the wellspring of Eris; /ultima discordia/ or
/discordia maximus/ if you well -- the opposite of
certainty.

And yet, our humble fnord is not unbound, it is a set of all
/possible/ causal chains, making possible maps.  The library
is not the territory and given that single gossamer strand
of hope to dangle from we can step back from the abyss and
use as the rock apon which we can build a rational universe.

A fnord is a cloud of all possible causal chains stemming
from any given assertion.  Like the Library of Babel is is
unimaginable unweildy, so it must remain a concept, a
/gedankenexperiment/ (literally a thought experiment) from
which we can contruct verifiable statements of facts.

Causal-chains are not all equal, they are either /possible/,
/probable/ or /improbable/ as well as being either /true/ or
/false/ given the context when they are observed.  When a
fnord is observed on one of each possible, probable or
improbable states becomes true or false.  And before any
[[https://en.wikipedia.org/wiki/Smart_aleck][smart aleck]] butts in with the obvious, if something true and
false at the same time, then /that/ is true.


So what can we take from all of this in order to build a real world
system?

  - Static data-structures can not be used to establish
    verifiable facts that we can rely on to be true
    statements, they must be dynamic systems that are
    dependent on an observer who is basically opening the
    box with Schrodinger's unfortunate cat is both alive and
    dead at the same time until we take a peak inside.

  - There are no simple statements of fact without a whole
    lot of other baggage that establishes it through
    definitions that work as tests which are processes.

  - Triples in the form of property values work, just not in
    isolation.


It is now obvious that there is no such thing as a simple
statement and that in fact when something is observed and
something becomes true or false, it still can not be stated
as a triple, but rather as a rhizomatic mesh of
interconnected statements that are the result of dynamic
processes that are executed that propagates through the mesh
every time something changes.  Our fnord describes the range
of posssible states that a mesh can be observed in, but we
don't have a way of describing those network of assertions
in themselves.  For this we need a new concept and
thankfully we won't have to come up with a new word.  A
perfectly good, though somewhat obscure, term already
exists: the holon.



